[2022-11-12T12:46:43.363+0000] {processor.py:154} INFO - Started process (PID=321) to work on /opt/airflow/dags/etl.py
[2022-11-12T12:46:43.367+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2022-11-12T12:46:43.375+0000] {logging_mixin.py:120} INFO - [2022-11-12T12:46:43.374+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2022-11-12T12:46:43.509+0000] {processor.py:766} INFO - DAG(s) dict_keys(['first_sample_dag']) retrieved from /opt/airflow/dags/etl.py
[2022-11-12T12:46:43.795+0000] {logging_mixin.py:120} INFO - [2022-11-12T12:46:43.794+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-12T12:46:43.894+0000] {logging_mixin.py:120} INFO - [2022-11-12T12:46:43.894+0000] {dag.py:3340} INFO - Setting next_dagrun for first_sample_dag to None, run_after=None
[2022-11-12T12:46:44.075+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/etl.py took 0.725 seconds
[2022-11-12T12:47:14.217+0000] {processor.py:154} INFO - Started process (PID=331) to work on /opt/airflow/dags/etl.py
[2022-11-12T12:47:14.226+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2022-11-12T12:47:14.234+0000] {logging_mixin.py:120} INFO - [2022-11-12T12:47:14.234+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2022-11-12T12:47:14.293+0000] {processor.py:766} INFO - DAG(s) dict_keys(['first_sample_dag']) retrieved from /opt/airflow/dags/etl.py
[2022-11-12T12:47:14.392+0000] {logging_mixin.py:120} INFO - [2022-11-12T12:47:14.392+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-12T12:47:14.540+0000] {logging_mixin.py:120} INFO - [2022-11-12T12:47:14.539+0000] {dag.py:3340} INFO - Setting next_dagrun for first_sample_dag to None, run_after=None
[2022-11-12T12:47:14.743+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/etl.py took 0.532 seconds
[2022-11-12T12:47:45.158+0000] {processor.py:154} INFO - Started process (PID=341) to work on /opt/airflow/dags/etl.py
[2022-11-12T12:47:45.163+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2022-11-12T12:47:45.166+0000] {logging_mixin.py:120} INFO - [2022-11-12T12:47:45.165+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2022-11-12T12:47:45.203+0000] {processor.py:766} INFO - DAG(s) dict_keys(['first_sample_dag']) retrieved from /opt/airflow/dags/etl.py
[2022-11-12T12:47:45.283+0000] {logging_mixin.py:120} INFO - [2022-11-12T12:47:45.283+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-12T12:47:45.384+0000] {logging_mixin.py:120} INFO - [2022-11-12T12:47:45.384+0000] {dag.py:3340} INFO - Setting next_dagrun for first_sample_dag to None, run_after=None
[2022-11-12T12:47:45.418+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/etl.py took 0.267 seconds
[2022-11-12T12:48:15.606+0000] {processor.py:154} INFO - Started process (PID=351) to work on /opt/airflow/dags/etl.py
[2022-11-12T12:48:15.615+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2022-11-12T12:48:15.618+0000] {logging_mixin.py:120} INFO - [2022-11-12T12:48:15.617+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2022-11-12T12:48:15.682+0000] {processor.py:766} INFO - DAG(s) dict_keys(['first_sample_dag']) retrieved from /opt/airflow/dags/etl.py
[2022-11-12T12:48:15.822+0000] {logging_mixin.py:120} INFO - [2022-11-12T12:48:15.822+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-12T12:48:15.861+0000] {logging_mixin.py:120} INFO - [2022-11-12T12:48:15.861+0000] {dag.py:3340} INFO - Setting next_dagrun for first_sample_dag to None, run_after=None
[2022-11-12T12:48:15.900+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/etl.py took 0.315 seconds
[2022-11-12T12:48:46.139+0000] {processor.py:154} INFO - Started process (PID=361) to work on /opt/airflow/dags/etl.py
[2022-11-12T12:48:46.144+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2022-11-12T12:48:46.147+0000] {logging_mixin.py:120} INFO - [2022-11-12T12:48:46.147+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2022-11-12T12:48:46.182+0000] {processor.py:766} INFO - DAG(s) dict_keys(['first_sample_dag']) retrieved from /opt/airflow/dags/etl.py
[2022-11-12T12:48:46.378+0000] {logging_mixin.py:120} INFO - [2022-11-12T12:48:46.378+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-12T12:48:46.466+0000] {logging_mixin.py:120} INFO - [2022-11-12T12:48:46.466+0000] {dag.py:3340} INFO - Setting next_dagrun for first_sample_dag to None, run_after=None
[2022-11-12T12:48:46.534+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/etl.py took 0.400 seconds
[2022-11-12T12:49:16.966+0000] {processor.py:154} INFO - Started process (PID=371) to work on /opt/airflow/dags/etl.py
[2022-11-12T12:49:16.991+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2022-11-12T12:49:16.996+0000] {logging_mixin.py:120} INFO - [2022-11-12T12:49:16.995+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2022-11-12T12:49:17.046+0000] {processor.py:766} INFO - DAG(s) dict_keys(['first_sample_dag']) retrieved from /opt/airflow/dags/etl.py
[2022-11-12T12:49:17.108+0000] {logging_mixin.py:120} INFO - [2022-11-12T12:49:17.107+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-12T12:49:17.190+0000] {logging_mixin.py:120} INFO - [2022-11-12T12:49:17.190+0000] {dag.py:3340} INFO - Setting next_dagrun for first_sample_dag to None, run_after=None
[2022-11-12T12:49:17.223+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/etl.py took 0.293 seconds
[2022-11-12T12:49:25.928+0000] {processor.py:154} INFO - Started process (PID=381) to work on /opt/airflow/dags/etl.py
[2022-11-12T12:49:25.956+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2022-11-12T12:49:25.993+0000] {logging_mixin.py:120} INFO - [2022-11-12T12:49:25.993+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2022-11-12T12:49:26.169+0000] {processor.py:766} INFO - DAG(s) dict_keys(['first_sample_dag']) retrieved from /opt/airflow/dags/etl.py
[2022-11-12T12:49:26.399+0000] {logging_mixin.py:120} INFO - [2022-11-12T12:49:26.399+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-12T12:49:26.525+0000] {logging_mixin.py:120} INFO - [2022-11-12T12:49:26.525+0000] {dag.py:3340} INFO - Setting next_dagrun for first_sample_dag to 2022-11-11T00:00:00+00:00, run_after=2022-11-12T00:00:00+00:00
[2022-11-12T12:49:26.777+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/etl.py took 0.886 seconds
[2022-11-12T12:52:11.874+0000] {processor.py:154} INFO - Started process (PID=176) to work on /opt/airflow/dags/etl.py
[2022-11-12T12:52:11.902+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2022-11-12T12:52:11.917+0000] {logging_mixin.py:120} INFO - [2022-11-12T12:52:11.917+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2022-11-12T12:52:12.237+0000] {processor.py:766} INFO - DAG(s) dict_keys(['first_sample_dag']) retrieved from /opt/airflow/dags/etl.py
[2022-11-12T12:52:14.742+0000] {logging_mixin.py:120} INFO - [2022-11-12T12:52:14.742+0000] {manager.py:510} ERROR - Creation of Permission View Error: (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "serialized_dag_pkey"
DETAIL:  Key (dag_id)=(first_sample_dag) already exists.

[SQL: INSERT INTO serialized_dag (dag_id, fileloc, fileloc_hash, data, data_compressed, last_updated, dag_hash, processor_subdir) VALUES (%(dag_id)s, %(fileloc)s, %(fileloc_hash)s, %(data)s, %(data_compressed)s, %(last_updated)s, %(dag_hash)s, %(processor_subdir)s)]
[parameters: {'dag_id': 'first_sample_dag', 'fileloc': '/opt/airflow/dags/etl.py', 'fileloc_hash': 34118401899435808, 'data': '{"__version": 1, "dag": {"_task_group": {"_group_id": null, "prefix_group_id": true, "tooltip": "", "ui_color": "CornflowerBlue", "ui_fgcolor": "#000 ... (2318 characters truncated) ... color": "#000", "_task_type": "EmptyOperator", "_task_module": "airflow.operators.empty", "_is_empty": true}], "dag_dependencies": [], "params": {}}}', 'data_compressed': None, 'last_updated': datetime.datetime(2022, 11, 12, 12, 52, 12, 423697, tzinfo=Timezone('UTC')), 'dag_hash': '66bb67f2c827d1aa0c7a8022eedc9226', 'processor_subdir': None}]
(Background on this error at: https://sqlalche.me/e/14/gkpj)
[2022-11-12T12:52:14.755+0000] {logging_mixin.py:120} INFO - [2022-11-12T12:52:14.754+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-12T12:52:14.872+0000] {logging_mixin.py:120} INFO - [2022-11-12T12:52:14.872+0000] {dag.py:2606} INFO - Creating ORM DAG for first_sample_dag
[2022-11-12T12:52:14.940+0000] {logging_mixin.py:120} INFO - [2022-11-12T12:52:14.940+0000] {dag.py:3340} INFO - Setting next_dagrun for first_sample_dag to 2022-11-11T00:00:00+00:00, run_after=2022-11-12T00:00:00+00:00
[2022-11-12T12:52:15.047+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/etl.py took 3.240 seconds
[2022-11-12T12:52:45.617+0000] {processor.py:154} INFO - Started process (PID=187) to work on /opt/airflow/dags/etl.py
[2022-11-12T12:52:45.635+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2022-11-12T12:52:45.638+0000] {logging_mixin.py:120} INFO - [2022-11-12T12:52:45.637+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2022-11-12T12:52:45.796+0000] {processor.py:766} INFO - DAG(s) dict_keys(['first_sample_dag']) retrieved from /opt/airflow/dags/etl.py
[2022-11-12T12:52:47.066+0000] {logging_mixin.py:120} INFO - [2022-11-12T12:52:47.065+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-12T12:52:47.207+0000] {logging_mixin.py:120} INFO - [2022-11-12T12:52:47.206+0000] {dag.py:3340} INFO - Setting next_dagrun for first_sample_dag to 2022-11-11T00:00:00+00:00, run_after=2022-11-12T00:00:00+00:00
[2022-11-12T12:52:47.420+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/etl.py took 1.816 seconds
[2022-11-12T12:53:18.004+0000] {processor.py:154} INFO - Started process (PID=202) to work on /opt/airflow/dags/etl.py
[2022-11-12T12:53:18.009+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2022-11-12T12:53:18.012+0000] {logging_mixin.py:120} INFO - [2022-11-12T12:53:18.011+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2022-11-12T12:53:18.073+0000] {processor.py:766} INFO - DAG(s) dict_keys(['first_sample_dag']) retrieved from /opt/airflow/dags/etl.py
[2022-11-12T12:53:18.420+0000] {logging_mixin.py:120} INFO - [2022-11-12T12:53:18.419+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-12T12:53:18.476+0000] {logging_mixin.py:120} INFO - [2022-11-12T12:53:18.476+0000] {dag.py:3340} INFO - Setting next_dagrun for first_sample_dag to 2022-11-11T00:00:00+00:00, run_after=2022-11-12T00:00:00+00:00
[2022-11-12T12:53:18.519+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/etl.py took 0.531 seconds
[2022-11-12T12:53:48.764+0000] {processor.py:154} INFO - Started process (PID=212) to work on /opt/airflow/dags/etl.py
[2022-11-12T12:53:48.767+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2022-11-12T12:53:48.769+0000] {logging_mixin.py:120} INFO - [2022-11-12T12:53:48.769+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2022-11-12T12:53:48.816+0000] {processor.py:766} INFO - DAG(s) dict_keys(['first_sample_dag']) retrieved from /opt/airflow/dags/etl.py
[2022-11-12T12:53:49.184+0000] {logging_mixin.py:120} INFO - [2022-11-12T12:53:49.184+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-12T12:53:49.242+0000] {logging_mixin.py:120} INFO - [2022-11-12T12:53:49.242+0000] {dag.py:3340} INFO - Setting next_dagrun for first_sample_dag to 2022-11-11T00:00:00+00:00, run_after=2022-11-12T00:00:00+00:00
[2022-11-12T12:53:49.291+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/etl.py took 0.533 seconds
[2022-11-12T12:54:19.700+0000] {processor.py:154} INFO - Started process (PID=220) to work on /opt/airflow/dags/etl.py
[2022-11-12T12:54:19.704+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2022-11-12T12:54:19.709+0000] {logging_mixin.py:120} INFO - [2022-11-12T12:54:19.709+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2022-11-12T12:54:20.032+0000] {processor.py:766} INFO - DAG(s) dict_keys(['first_sample_dag']) retrieved from /opt/airflow/dags/etl.py
[2022-11-12T12:54:20.071+0000] {logging_mixin.py:120} INFO - [2022-11-12T12:54:20.071+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-12T12:54:20.118+0000] {logging_mixin.py:120} INFO - [2022-11-12T12:54:20.118+0000] {dag.py:3340} INFO - Setting next_dagrun for first_sample_dag to 2022-11-11T00:00:00+00:00, run_after=2022-11-12T00:00:00+00:00
[2022-11-12T12:54:20.158+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/etl.py took 0.468 seconds
[2022-11-12T12:54:50.743+0000] {processor.py:154} INFO - Started process (PID=227) to work on /opt/airflow/dags/etl.py
[2022-11-12T12:54:50.752+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2022-11-12T12:54:50.759+0000] {logging_mixin.py:120} INFO - [2022-11-12T12:54:50.758+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2022-11-12T12:54:51.656+0000] {processor.py:766} INFO - DAG(s) dict_keys(['first_sample_dag']) retrieved from /opt/airflow/dags/etl.py
[2022-11-12T12:54:52.215+0000] {logging_mixin.py:120} INFO - [2022-11-12T12:54:52.213+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-12T12:54:52.385+0000] {logging_mixin.py:120} INFO - [2022-11-12T12:54:52.385+0000] {dag.py:3340} INFO - Setting next_dagrun for first_sample_dag to 2022-11-11T00:00:00+00:00, run_after=2022-11-12T00:00:00+00:00
[2022-11-12T12:54:52.471+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/etl.py took 1.766 seconds
[2022-11-12T12:55:22.761+0000] {processor.py:154} INFO - Started process (PID=237) to work on /opt/airflow/dags/etl.py
[2022-11-12T12:55:22.765+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2022-11-12T12:55:22.768+0000] {logging_mixin.py:120} INFO - [2022-11-12T12:55:22.768+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2022-11-12T12:55:22.937+0000] {processor.py:766} INFO - DAG(s) dict_keys(['first_sample_dag']) retrieved from /opt/airflow/dags/etl.py
[2022-11-12T12:55:23.138+0000] {logging_mixin.py:120} INFO - [2022-11-12T12:55:23.138+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-12T12:55:23.387+0000] {logging_mixin.py:120} INFO - [2022-11-12T12:55:23.387+0000] {dag.py:3340} INFO - Setting next_dagrun for first_sample_dag to 2022-11-11T00:00:00+00:00, run_after=2022-11-12T00:00:00+00:00
[2022-11-12T12:55:23.555+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/etl.py took 0.819 seconds
[2022-11-12T12:55:33.872+0000] {processor.py:154} INFO - Started process (PID=247) to work on /opt/airflow/dags/etl.py
[2022-11-12T12:55:33.875+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2022-11-12T12:55:33.880+0000] {logging_mixin.py:120} INFO - [2022-11-12T12:55:33.879+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2022-11-12T12:55:33.988+0000] {processor.py:766} INFO - DAG(s) dict_keys(['ETL']) retrieved from /opt/airflow/dags/etl.py
[2022-11-12T12:55:34.386+0000] {logging_mixin.py:120} INFO - [2022-11-12T12:55:34.385+0000] {manager.py:507} INFO - Created Permission View: can delete on DAG:ETL
[2022-11-12T12:55:34.405+0000] {logging_mixin.py:120} INFO - [2022-11-12T12:55:34.405+0000] {manager.py:507} INFO - Created Permission View: can edit on DAG:ETL
[2022-11-12T12:55:34.425+0000] {logging_mixin.py:120} INFO - [2022-11-12T12:55:34.425+0000] {manager.py:507} INFO - Created Permission View: can read on DAG:ETL
[2022-11-12T12:55:34.428+0000] {logging_mixin.py:120} INFO - [2022-11-12T12:55:34.428+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-12T12:55:34.470+0000] {logging_mixin.py:120} INFO - [2022-11-12T12:55:34.469+0000] {dag.py:2606} INFO - Creating ORM DAG for ETL
[2022-11-12T12:55:34.528+0000] {logging_mixin.py:120} INFO - [2022-11-12T12:55:34.526+0000] {dag.py:3340} INFO - Setting next_dagrun for ETL to 2022-11-11T00:00:00+00:00, run_after=2022-11-12T00:00:00+00:00
[2022-11-12T12:55:34.590+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/etl.py took 0.731 seconds
[2022-11-12T12:58:01.024+0000] {processor.py:154} INFO - Started process (PID=177) to work on /opt/airflow/dags/etl.py
[2022-11-12T12:58:01.103+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2022-11-12T12:58:01.121+0000] {logging_mixin.py:120} INFO - [2022-11-12T12:58:01.120+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2022-11-12T12:58:01.733+0000] {processor.py:766} INFO - DAG(s) dict_keys(['ETL']) retrieved from /opt/airflow/dags/etl.py
[2022-11-12T12:58:04.117+0000] {logging_mixin.py:120} INFO - [2022-11-12T12:58:04.115+0000] {manager.py:507} INFO - Created Permission View: can read on DAG:ETL
[2022-11-12T12:58:04.141+0000] {logging_mixin.py:120} INFO - [2022-11-12T12:58:04.141+0000] {manager.py:507} INFO - Created Permission View: can edit on DAG:ETL
[2022-11-12T12:58:04.158+0000] {logging_mixin.py:120} INFO - [2022-11-12T12:58:04.156+0000] {manager.py:507} INFO - Created Permission View: can delete on DAG:ETL
[2022-11-12T12:58:04.163+0000] {logging_mixin.py:120} INFO - [2022-11-12T12:58:04.162+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-12T12:58:04.206+0000] {logging_mixin.py:120} INFO - [2022-11-12T12:58:04.206+0000] {dag.py:2606} INFO - Creating ORM DAG for ETL
[2022-11-12T12:58:04.275+0000] {logging_mixin.py:120} INFO - [2022-11-12T12:58:04.273+0000] {dag.py:3340} INFO - Setting next_dagrun for ETL to 2022-11-11T00:00:00+00:00, run_after=2022-11-12T00:00:00+00:00
[2022-11-12T12:58:04.372+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/etl.py took 3.655 seconds
[2022-11-12T12:58:35.153+0000] {processor.py:154} INFO - Started process (PID=190) to work on /opt/airflow/dags/etl.py
[2022-11-12T12:58:35.163+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2022-11-12T12:58:35.178+0000] {logging_mixin.py:120} INFO - [2022-11-12T12:58:35.170+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2022-11-12T12:58:35.578+0000] {processor.py:766} INFO - DAG(s) dict_keys(['ETL']) retrieved from /opt/airflow/dags/etl.py
[2022-11-12T12:58:36.277+0000] {logging_mixin.py:120} INFO - [2022-11-12T12:58:36.276+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-12T12:58:36.404+0000] {logging_mixin.py:120} INFO - [2022-11-12T12:58:36.404+0000] {dag.py:3340} INFO - Setting next_dagrun for ETL to 2022-11-11T00:00:00+00:00, run_after=2022-11-12T00:00:00+00:00
[2022-11-12T12:58:36.561+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/etl.py took 1.463 seconds
[2022-11-12T12:59:06.953+0000] {processor.py:154} INFO - Started process (PID=200) to work on /opt/airflow/dags/etl.py
[2022-11-12T12:59:06.958+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2022-11-12T12:59:06.967+0000] {logging_mixin.py:120} INFO - [2022-11-12T12:59:06.965+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2022-11-12T12:59:07.133+0000] {processor.py:766} INFO - DAG(s) dict_keys(['ETL']) retrieved from /opt/airflow/dags/etl.py
[2022-11-12T12:59:07.627+0000] {logging_mixin.py:120} INFO - [2022-11-12T12:59:07.626+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-12T12:59:07.724+0000] {logging_mixin.py:120} INFO - [2022-11-12T12:59:07.723+0000] {dag.py:3340} INFO - Setting next_dagrun for ETL to 2022-11-11T00:00:00+00:00, run_after=2022-11-12T00:00:00+00:00
[2022-11-12T12:59:07.848+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/etl.py took 0.914 seconds
[2022-11-12T12:59:38.835+0000] {processor.py:154} INFO - Started process (PID=210) to work on /opt/airflow/dags/etl.py
[2022-11-12T12:59:38.870+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2022-11-12T12:59:38.888+0000] {logging_mixin.py:120} INFO - [2022-11-12T12:59:38.883+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2022-11-12T12:59:39.026+0000] {processor.py:766} INFO - DAG(s) dict_keys(['ETL']) retrieved from /opt/airflow/dags/etl.py
[2022-11-12T12:59:39.837+0000] {logging_mixin.py:120} INFO - [2022-11-12T12:59:39.836+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-12T12:59:39.943+0000] {logging_mixin.py:120} INFO - [2022-11-12T12:59:39.943+0000] {dag.py:3340} INFO - Setting next_dagrun for ETL to 2022-11-11T00:00:00+00:00, run_after=2022-11-12T00:00:00+00:00
[2022-11-12T12:59:40.029+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/etl.py took 1.295 seconds
[2022-11-12T13:00:10.344+0000] {processor.py:154} INFO - Started process (PID=220) to work on /opt/airflow/dags/etl.py
[2022-11-12T13:00:10.351+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2022-11-12T13:00:10.361+0000] {logging_mixin.py:120} INFO - [2022-11-12T13:00:10.360+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2022-11-12T13:00:11.226+0000] {processor.py:766} INFO - DAG(s) dict_keys(['ETL']) retrieved from /opt/airflow/dags/etl.py
[2022-11-12T13:00:11.364+0000] {logging_mixin.py:120} INFO - [2022-11-12T13:00:11.363+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-12T13:00:11.505+0000] {logging_mixin.py:120} INFO - [2022-11-12T13:00:11.505+0000] {dag.py:3340} INFO - Setting next_dagrun for ETL to 2022-11-11T00:00:00+00:00, run_after=2022-11-12T00:00:00+00:00
[2022-11-12T13:00:11.646+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/etl.py took 1.354 seconds
[2022-11-12T13:00:42.414+0000] {processor.py:154} INFO - Started process (PID=236) to work on /opt/airflow/dags/etl.py
[2022-11-12T13:00:42.437+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2022-11-12T13:00:42.444+0000] {logging_mixin.py:120} INFO - [2022-11-12T13:00:42.443+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2022-11-12T13:00:43.461+0000] {processor.py:766} INFO - DAG(s) dict_keys(['ETL']) retrieved from /opt/airflow/dags/etl.py
[2022-11-12T13:00:43.606+0000] {logging_mixin.py:120} INFO - [2022-11-12T13:00:43.605+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-12T13:00:43.701+0000] {logging_mixin.py:120} INFO - [2022-11-12T13:00:43.700+0000] {dag.py:3340} INFO - Setting next_dagrun for ETL to 2022-11-12T00:00:00+00:00, run_after=2022-11-13T00:00:00+00:00
[2022-11-12T13:00:43.757+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/etl.py took 1.362 seconds
[2022-11-12T13:01:14.038+0000] {processor.py:154} INFO - Started process (PID=248) to work on /opt/airflow/dags/etl.py
[2022-11-12T13:01:14.046+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2022-11-12T13:01:14.053+0000] {logging_mixin.py:120} INFO - [2022-11-12T13:01:14.052+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2022-11-12T13:01:14.147+0000] {processor.py:766} INFO - DAG(s) dict_keys(['ETL']) retrieved from /opt/airflow/dags/etl.py
[2022-11-12T13:01:14.447+0000] {logging_mixin.py:120} INFO - [2022-11-12T13:01:14.446+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-12T13:01:14.587+0000] {logging_mixin.py:120} INFO - [2022-11-12T13:01:14.585+0000] {dag.py:3340} INFO - Setting next_dagrun for ETL to 2022-11-12T00:00:00+00:00, run_after=2022-11-13T00:00:00+00:00
[2022-11-12T13:01:14.715+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/etl.py took 0.683 seconds
[2022-11-12T13:01:45.108+0000] {processor.py:154} INFO - Started process (PID=258) to work on /opt/airflow/dags/etl.py
[2022-11-12T13:01:45.114+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2022-11-12T13:01:45.123+0000] {logging_mixin.py:120} INFO - [2022-11-12T13:01:45.123+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2022-11-12T13:01:45.203+0000] {processor.py:766} INFO - DAG(s) dict_keys(['ETL']) retrieved from /opt/airflow/dags/etl.py
[2022-11-12T13:01:45.306+0000] {logging_mixin.py:120} INFO - [2022-11-12T13:01:45.306+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-12T13:01:45.399+0000] {logging_mixin.py:120} INFO - [2022-11-12T13:01:45.397+0000] {dag.py:3340} INFO - Setting next_dagrun for ETL to 2022-11-12T00:00:00+00:00, run_after=2022-11-13T00:00:00+00:00
[2022-11-12T13:01:45.573+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/etl.py took 0.469 seconds
[2022-11-12T13:02:15.923+0000] {processor.py:154} INFO - Started process (PID=268) to work on /opt/airflow/dags/etl.py
[2022-11-12T13:02:15.929+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2022-11-12T13:02:15.932+0000] {logging_mixin.py:120} INFO - [2022-11-12T13:02:15.932+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2022-11-12T13:02:15.973+0000] {processor.py:766} INFO - DAG(s) dict_keys(['ETL']) retrieved from /opt/airflow/dags/etl.py
[2022-11-12T13:02:16.039+0000] {logging_mixin.py:120} INFO - [2022-11-12T13:02:16.038+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-12T13:02:16.081+0000] {logging_mixin.py:120} INFO - [2022-11-12T13:02:16.081+0000] {dag.py:3340} INFO - Setting next_dagrun for ETL to 2022-11-12T00:00:00+00:00, run_after=2022-11-13T00:00:00+00:00
[2022-11-12T13:02:16.129+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/etl.py took 0.218 seconds
[2022-11-12T13:02:46.357+0000] {processor.py:154} INFO - Started process (PID=278) to work on /opt/airflow/dags/etl.py
[2022-11-12T13:02:46.359+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2022-11-12T13:02:46.361+0000] {logging_mixin.py:120} INFO - [2022-11-12T13:02:46.361+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2022-11-12T13:02:46.396+0000] {processor.py:766} INFO - DAG(s) dict_keys(['ETL']) retrieved from /opt/airflow/dags/etl.py
[2022-11-12T13:02:46.457+0000] {logging_mixin.py:120} INFO - [2022-11-12T13:02:46.456+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-12T13:02:46.504+0000] {logging_mixin.py:120} INFO - [2022-11-12T13:02:46.503+0000] {dag.py:3340} INFO - Setting next_dagrun for ETL to 2022-11-12T00:00:00+00:00, run_after=2022-11-13T00:00:00+00:00
[2022-11-12T13:02:46.571+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/etl.py took 0.219 seconds
[2022-11-12T13:03:16.699+0000] {processor.py:154} INFO - Started process (PID=283) to work on /opt/airflow/dags/etl.py
[2022-11-12T13:03:16.702+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2022-11-12T13:03:16.705+0000] {logging_mixin.py:120} INFO - [2022-11-12T13:03:16.704+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2022-11-12T13:03:16.753+0000] {processor.py:766} INFO - DAG(s) dict_keys(['ETL']) retrieved from /opt/airflow/dags/etl.py
[2022-11-12T13:03:16.834+0000] {logging_mixin.py:120} INFO - [2022-11-12T13:03:16.834+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-12T13:03:16.897+0000] {logging_mixin.py:120} INFO - [2022-11-12T13:03:16.896+0000] {dag.py:3340} INFO - Setting next_dagrun for ETL to 2022-11-12T00:00:00+00:00, run_after=2022-11-13T00:00:00+00:00
[2022-11-12T13:03:16.929+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/etl.py took 0.243 seconds
[2022-11-12T13:03:47.136+0000] {processor.py:154} INFO - Started process (PID=293) to work on /opt/airflow/dags/etl.py
[2022-11-12T13:03:47.139+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2022-11-12T13:03:47.141+0000] {logging_mixin.py:120} INFO - [2022-11-12T13:03:47.141+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2022-11-12T13:03:47.205+0000] {processor.py:766} INFO - DAG(s) dict_keys(['ETL']) retrieved from /opt/airflow/dags/etl.py
[2022-11-12T13:03:47.272+0000] {logging_mixin.py:120} INFO - [2022-11-12T13:03:47.272+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-12T13:03:47.317+0000] {logging_mixin.py:120} INFO - [2022-11-12T13:03:47.317+0000] {dag.py:3340} INFO - Setting next_dagrun for ETL to 2022-11-12T00:00:00+00:00, run_after=2022-11-13T00:00:00+00:00
[2022-11-12T13:03:47.345+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/etl.py took 0.215 seconds
[2022-11-12T13:04:17.608+0000] {processor.py:154} INFO - Started process (PID=303) to work on /opt/airflow/dags/etl.py
[2022-11-12T13:04:17.611+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2022-11-12T13:04:17.613+0000] {logging_mixin.py:120} INFO - [2022-11-12T13:04:17.613+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2022-11-12T13:04:17.663+0000] {processor.py:766} INFO - DAG(s) dict_keys(['ETL']) retrieved from /opt/airflow/dags/etl.py
[2022-11-12T13:04:17.751+0000] {logging_mixin.py:120} INFO - [2022-11-12T13:04:17.751+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-12T13:04:17.798+0000] {logging_mixin.py:120} INFO - [2022-11-12T13:04:17.798+0000] {dag.py:3340} INFO - Setting next_dagrun for ETL to 2022-11-12T00:00:00+00:00, run_after=2022-11-13T00:00:00+00:00
[2022-11-12T13:04:17.832+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/etl.py took 0.232 seconds
[2022-11-12T13:04:48.071+0000] {processor.py:154} INFO - Started process (PID=313) to work on /opt/airflow/dags/etl.py
[2022-11-12T13:04:48.075+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2022-11-12T13:04:48.086+0000] {logging_mixin.py:120} INFO - [2022-11-12T13:04:48.085+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2022-11-12T13:04:48.350+0000] {processor.py:766} INFO - DAG(s) dict_keys(['ETL']) retrieved from /opt/airflow/dags/etl.py
[2022-11-12T13:04:48.948+0000] {logging_mixin.py:120} INFO - [2022-11-12T13:04:48.947+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-12T13:04:49.067+0000] {logging_mixin.py:120} INFO - [2022-11-12T13:04:49.067+0000] {dag.py:3340} INFO - Setting next_dagrun for ETL to 2022-11-12T00:00:00+00:00, run_after=2022-11-13T00:00:00+00:00
[2022-11-12T13:04:49.118+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/etl.py took 1.057 seconds
[2022-11-12T13:05:19.502+0000] {processor.py:154} INFO - Started process (PID=323) to work on /opt/airflow/dags/etl.py
[2022-11-12T13:05:19.505+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2022-11-12T13:05:19.507+0000] {logging_mixin.py:120} INFO - [2022-11-12T13:05:19.507+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2022-11-12T13:05:19.550+0000] {processor.py:766} INFO - DAG(s) dict_keys(['ETL']) retrieved from /opt/airflow/dags/etl.py
[2022-11-12T13:05:19.619+0000] {logging_mixin.py:120} INFO - [2022-11-12T13:05:19.619+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-12T13:05:19.701+0000] {logging_mixin.py:120} INFO - [2022-11-12T13:05:19.701+0000] {dag.py:3340} INFO - Setting next_dagrun for ETL to 2022-11-12T00:00:00+00:00, run_after=2022-11-13T00:00:00+00:00
[2022-11-12T13:05:19.737+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/etl.py took 0.240 seconds
[2022-11-12T13:05:49.991+0000] {processor.py:154} INFO - Started process (PID=333) to work on /opt/airflow/dags/etl.py
[2022-11-12T13:05:50.002+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2022-11-12T13:05:50.008+0000] {logging_mixin.py:120} INFO - [2022-11-12T13:05:50.007+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2022-11-12T13:05:50.067+0000] {processor.py:766} INFO - DAG(s) dict_keys(['ETL']) retrieved from /opt/airflow/dags/etl.py
[2022-11-12T13:05:50.169+0000] {logging_mixin.py:120} INFO - [2022-11-12T13:05:50.169+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-12T13:05:50.256+0000] {logging_mixin.py:120} INFO - [2022-11-12T13:05:50.256+0000] {dag.py:3340} INFO - Setting next_dagrun for ETL to 2022-11-12T00:00:00+00:00, run_after=2022-11-13T00:00:00+00:00
[2022-11-12T13:05:50.301+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/etl.py took 0.322 seconds
[2022-11-12T13:06:20.508+0000] {processor.py:154} INFO - Started process (PID=343) to work on /opt/airflow/dags/etl.py
[2022-11-12T13:06:20.510+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2022-11-12T13:06:20.513+0000] {logging_mixin.py:120} INFO - [2022-11-12T13:06:20.513+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2022-11-12T13:06:20.565+0000] {processor.py:766} INFO - DAG(s) dict_keys(['ETL']) retrieved from /opt/airflow/dags/etl.py
[2022-11-12T13:06:20.647+0000] {logging_mixin.py:120} INFO - [2022-11-12T13:06:20.647+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-12T13:06:20.712+0000] {logging_mixin.py:120} INFO - [2022-11-12T13:06:20.712+0000] {dag.py:3340} INFO - Setting next_dagrun for ETL to 2022-11-12T00:00:00+00:00, run_after=2022-11-13T00:00:00+00:00
[2022-11-12T13:06:20.748+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/etl.py took 0.248 seconds
[2022-11-12T13:06:51.006+0000] {processor.py:154} INFO - Started process (PID=353) to work on /opt/airflow/dags/etl.py
[2022-11-12T13:06:51.008+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2022-11-12T13:06:51.010+0000] {logging_mixin.py:120} INFO - [2022-11-12T13:06:51.010+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2022-11-12T13:06:51.100+0000] {processor.py:766} INFO - DAG(s) dict_keys(['ETL']) retrieved from /opt/airflow/dags/etl.py
[2022-11-12T13:06:51.175+0000] {logging_mixin.py:120} INFO - [2022-11-12T13:06:51.174+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-12T13:06:51.223+0000] {logging_mixin.py:120} INFO - [2022-11-12T13:06:51.223+0000] {dag.py:3340} INFO - Setting next_dagrun for ETL to 2022-11-12T00:00:00+00:00, run_after=2022-11-13T00:00:00+00:00
[2022-11-12T13:06:51.256+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/etl.py took 0.257 seconds
[2022-11-12T13:07:21.502+0000] {processor.py:154} INFO - Started process (PID=363) to work on /opt/airflow/dags/etl.py
[2022-11-12T13:07:21.504+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2022-11-12T13:07:21.508+0000] {logging_mixin.py:120} INFO - [2022-11-12T13:07:21.507+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2022-11-12T13:07:21.560+0000] {processor.py:766} INFO - DAG(s) dict_keys(['ETL']) retrieved from /opt/airflow/dags/etl.py
[2022-11-12T13:07:21.630+0000] {logging_mixin.py:120} INFO - [2022-11-12T13:07:21.629+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-12T13:07:21.670+0000] {logging_mixin.py:120} INFO - [2022-11-12T13:07:21.669+0000] {dag.py:3340} INFO - Setting next_dagrun for ETL to 2022-11-12T00:00:00+00:00, run_after=2022-11-13T00:00:00+00:00
[2022-11-12T13:07:21.706+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/etl.py took 0.213 seconds
[2022-11-12T13:07:51.982+0000] {processor.py:154} INFO - Started process (PID=373) to work on /opt/airflow/dags/etl.py
[2022-11-12T13:07:51.988+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2022-11-12T13:07:51.994+0000] {logging_mixin.py:120} INFO - [2022-11-12T13:07:51.993+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2022-11-12T13:07:52.078+0000] {processor.py:766} INFO - DAG(s) dict_keys(['ETL']) retrieved from /opt/airflow/dags/etl.py
[2022-11-12T13:07:52.204+0000] {logging_mixin.py:120} INFO - [2022-11-12T13:07:52.203+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-12T13:07:52.300+0000] {logging_mixin.py:120} INFO - [2022-11-12T13:07:52.300+0000] {dag.py:3340} INFO - Setting next_dagrun for ETL to 2022-11-12T00:00:00+00:00, run_after=2022-11-13T00:00:00+00:00
[2022-11-12T13:07:52.358+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/etl.py took 0.389 seconds
[2022-11-12T13:08:22.661+0000] {processor.py:154} INFO - Started process (PID=383) to work on /opt/airflow/dags/etl.py
[2022-11-12T13:08:22.667+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2022-11-12T13:08:22.669+0000] {logging_mixin.py:120} INFO - [2022-11-12T13:08:22.669+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2022-11-12T13:08:22.725+0000] {processor.py:766} INFO - DAG(s) dict_keys(['ETL']) retrieved from /opt/airflow/dags/etl.py
[2022-11-12T13:08:22.800+0000] {logging_mixin.py:120} INFO - [2022-11-12T13:08:22.800+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-12T13:08:22.851+0000] {logging_mixin.py:120} INFO - [2022-11-12T13:08:22.851+0000] {dag.py:3340} INFO - Setting next_dagrun for ETL to 2022-11-12T00:00:00+00:00, run_after=2022-11-13T00:00:00+00:00
[2022-11-12T13:08:22.899+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/etl.py took 0.245 seconds
[2022-11-12T13:08:53.134+0000] {processor.py:154} INFO - Started process (PID=393) to work on /opt/airflow/dags/etl.py
[2022-11-12T13:08:53.136+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2022-11-12T13:08:53.139+0000] {logging_mixin.py:120} INFO - [2022-11-12T13:08:53.139+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2022-11-12T13:08:53.227+0000] {processor.py:766} INFO - DAG(s) dict_keys(['ETL']) retrieved from /opt/airflow/dags/etl.py
[2022-11-12T13:08:53.424+0000] {logging_mixin.py:120} INFO - [2022-11-12T13:08:53.424+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-12T13:08:53.465+0000] {logging_mixin.py:120} INFO - [2022-11-12T13:08:53.465+0000] {dag.py:3340} INFO - Setting next_dagrun for ETL to 2022-11-12T00:00:00+00:00, run_after=2022-11-13T00:00:00+00:00
[2022-11-12T13:08:53.497+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/etl.py took 0.372 seconds
[2022-11-12T13:09:23.766+0000] {processor.py:154} INFO - Started process (PID=403) to work on /opt/airflow/dags/etl.py
[2022-11-12T13:09:23.769+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2022-11-12T13:09:23.772+0000] {logging_mixin.py:120} INFO - [2022-11-12T13:09:23.771+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2022-11-12T13:09:23.826+0000] {processor.py:766} INFO - DAG(s) dict_keys(['ETL']) retrieved from /opt/airflow/dags/etl.py
[2022-11-12T13:09:23.906+0000] {logging_mixin.py:120} INFO - [2022-11-12T13:09:23.906+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-12T13:09:23.954+0000] {logging_mixin.py:120} INFO - [2022-11-12T13:09:23.954+0000] {dag.py:3340} INFO - Setting next_dagrun for ETL to 2022-11-12T00:00:00+00:00, run_after=2022-11-13T00:00:00+00:00
[2022-11-12T13:09:24.007+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/etl.py took 0.254 seconds
[2022-11-12T13:09:54.284+0000] {processor.py:154} INFO - Started process (PID=413) to work on /opt/airflow/dags/etl.py
[2022-11-12T13:09:54.288+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2022-11-12T13:09:54.292+0000] {logging_mixin.py:120} INFO - [2022-11-12T13:09:54.292+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2022-11-12T13:09:54.367+0000] {processor.py:766} INFO - DAG(s) dict_keys(['ETL']) retrieved from /opt/airflow/dags/etl.py
[2022-11-12T13:09:54.482+0000] {logging_mixin.py:120} INFO - [2022-11-12T13:09:54.481+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-12T13:09:54.566+0000] {logging_mixin.py:120} INFO - [2022-11-12T13:09:54.566+0000] {dag.py:3340} INFO - Setting next_dagrun for ETL to 2022-11-12T00:00:00+00:00, run_after=2022-11-13T00:00:00+00:00
[2022-11-12T13:09:54.607+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/etl.py took 0.335 seconds
[2022-11-12T13:10:24.848+0000] {processor.py:154} INFO - Started process (PID=423) to work on /opt/airflow/dags/etl.py
[2022-11-12T13:10:24.853+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2022-11-12T13:10:24.856+0000] {logging_mixin.py:120} INFO - [2022-11-12T13:10:24.856+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2022-11-12T13:10:24.953+0000] {processor.py:766} INFO - DAG(s) dict_keys(['ETL']) retrieved from /opt/airflow/dags/etl.py
[2022-11-12T13:10:25.064+0000] {logging_mixin.py:120} INFO - [2022-11-12T13:10:25.062+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-12T13:10:25.111+0000] {logging_mixin.py:120} INFO - [2022-11-12T13:10:25.110+0000] {dag.py:3340} INFO - Setting next_dagrun for ETL to 2022-11-12T00:00:00+00:00, run_after=2022-11-13T00:00:00+00:00
[2022-11-12T13:10:25.151+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/etl.py took 0.314 seconds
[2022-11-12T13:10:55.404+0000] {processor.py:154} INFO - Started process (PID=433) to work on /opt/airflow/dags/etl.py
[2022-11-12T13:10:55.410+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2022-11-12T13:10:55.413+0000] {logging_mixin.py:120} INFO - [2022-11-12T13:10:55.413+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2022-11-12T13:10:55.466+0000] {processor.py:766} INFO - DAG(s) dict_keys(['ETL']) retrieved from /opt/airflow/dags/etl.py
[2022-11-12T13:10:55.534+0000] {logging_mixin.py:120} INFO - [2022-11-12T13:10:55.534+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-12T13:10:55.578+0000] {logging_mixin.py:120} INFO - [2022-11-12T13:10:55.577+0000] {dag.py:3340} INFO - Setting next_dagrun for ETL to 2022-11-12T00:00:00+00:00, run_after=2022-11-13T00:00:00+00:00
[2022-11-12T13:10:55.617+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/etl.py took 0.222 seconds
[2022-11-12T13:11:25.891+0000] {processor.py:154} INFO - Started process (PID=443) to work on /opt/airflow/dags/etl.py
[2022-11-12T13:11:25.908+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2022-11-12T13:11:25.916+0000] {logging_mixin.py:120} INFO - [2022-11-12T13:11:25.915+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2022-11-12T13:11:25.984+0000] {processor.py:766} INFO - DAG(s) dict_keys(['ETL']) retrieved from /opt/airflow/dags/etl.py
[2022-11-12T13:11:26.055+0000] {logging_mixin.py:120} INFO - [2022-11-12T13:11:26.054+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-12T13:11:26.101+0000] {logging_mixin.py:120} INFO - [2022-11-12T13:11:26.101+0000] {dag.py:3340} INFO - Setting next_dagrun for ETL to 2022-11-12T00:00:00+00:00, run_after=2022-11-13T00:00:00+00:00
[2022-11-12T13:11:26.149+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/etl.py took 0.266 seconds
[2022-11-12T13:11:56.411+0000] {processor.py:154} INFO - Started process (PID=453) to work on /opt/airflow/dags/etl.py
[2022-11-12T13:11:56.414+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2022-11-12T13:11:56.419+0000] {logging_mixin.py:120} INFO - [2022-11-12T13:11:56.418+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2022-11-12T13:11:56.468+0000] {processor.py:766} INFO - DAG(s) dict_keys(['ETL']) retrieved from /opt/airflow/dags/etl.py
[2022-11-12T13:11:56.544+0000] {logging_mixin.py:120} INFO - [2022-11-12T13:11:56.544+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-12T13:11:56.592+0000] {logging_mixin.py:120} INFO - [2022-11-12T13:11:56.592+0000] {dag.py:3340} INFO - Setting next_dagrun for ETL to 2022-11-12T00:00:00+00:00, run_after=2022-11-13T00:00:00+00:00
[2022-11-12T13:11:56.635+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/etl.py took 0.236 seconds
[2022-11-12T13:12:26.880+0000] {processor.py:154} INFO - Started process (PID=463) to work on /opt/airflow/dags/etl.py
[2022-11-12T13:12:26.884+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2022-11-12T13:12:26.887+0000] {logging_mixin.py:120} INFO - [2022-11-12T13:12:26.887+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2022-11-12T13:12:26.944+0000] {processor.py:766} INFO - DAG(s) dict_keys(['ETL']) retrieved from /opt/airflow/dags/etl.py
[2022-11-12T13:12:27.020+0000] {logging_mixin.py:120} INFO - [2022-11-12T13:12:27.020+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-12T13:12:27.069+0000] {logging_mixin.py:120} INFO - [2022-11-12T13:12:27.068+0000] {dag.py:3340} INFO - Setting next_dagrun for ETL to 2022-11-12T00:00:00+00:00, run_after=2022-11-13T00:00:00+00:00
[2022-11-12T13:12:27.110+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/etl.py took 0.240 seconds
[2022-11-12T13:12:57.396+0000] {processor.py:154} INFO - Started process (PID=473) to work on /opt/airflow/dags/etl.py
[2022-11-12T13:12:57.400+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2022-11-12T13:12:57.402+0000] {logging_mixin.py:120} INFO - [2022-11-12T13:12:57.401+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2022-11-12T13:12:57.460+0000] {processor.py:766} INFO - DAG(s) dict_keys(['ETL']) retrieved from /opt/airflow/dags/etl.py
[2022-11-12T13:12:57.530+0000] {logging_mixin.py:120} INFO - [2022-11-12T13:12:57.529+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-12T13:12:57.571+0000] {logging_mixin.py:120} INFO - [2022-11-12T13:12:57.571+0000] {dag.py:3340} INFO - Setting next_dagrun for ETL to 2022-11-12T00:00:00+00:00, run_after=2022-11-13T00:00:00+00:00
[2022-11-12T13:12:57.602+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/etl.py took 0.213 seconds
[2022-11-12T13:13:27.903+0000] {processor.py:154} INFO - Started process (PID=483) to work on /opt/airflow/dags/etl.py
[2022-11-12T13:13:27.906+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2022-11-12T13:13:27.910+0000] {logging_mixin.py:120} INFO - [2022-11-12T13:13:27.909+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2022-11-12T13:13:27.963+0000] {processor.py:766} INFO - DAG(s) dict_keys(['ETL']) retrieved from /opt/airflow/dags/etl.py
[2022-11-12T13:13:28.064+0000] {logging_mixin.py:120} INFO - [2022-11-12T13:13:28.064+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-12T13:13:28.112+0000] {logging_mixin.py:120} INFO - [2022-11-12T13:13:28.112+0000] {dag.py:3340} INFO - Setting next_dagrun for ETL to 2022-11-12T00:00:00+00:00, run_after=2022-11-13T00:00:00+00:00
[2022-11-12T13:13:28.207+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/etl.py took 0.312 seconds
[2022-11-12T13:13:58.450+0000] {processor.py:154} INFO - Started process (PID=493) to work on /opt/airflow/dags/etl.py
[2022-11-12T13:13:58.452+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2022-11-12T13:13:58.454+0000] {logging_mixin.py:120} INFO - [2022-11-12T13:13:58.454+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2022-11-12T13:13:58.513+0000] {processor.py:766} INFO - DAG(s) dict_keys(['ETL']) retrieved from /opt/airflow/dags/etl.py
[2022-11-12T13:13:58.577+0000] {logging_mixin.py:120} INFO - [2022-11-12T13:13:58.577+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-12T13:13:58.622+0000] {logging_mixin.py:120} INFO - [2022-11-12T13:13:58.622+0000] {dag.py:3340} INFO - Setting next_dagrun for ETL to 2022-11-12T00:00:00+00:00, run_after=2022-11-13T00:00:00+00:00
[2022-11-12T13:13:58.650+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/etl.py took 0.206 seconds
[2022-11-12T13:14:28.929+0000] {processor.py:154} INFO - Started process (PID=503) to work on /opt/airflow/dags/etl.py
[2022-11-12T13:14:28.932+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2022-11-12T13:14:28.935+0000] {logging_mixin.py:120} INFO - [2022-11-12T13:14:28.935+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2022-11-12T13:14:28.990+0000] {processor.py:766} INFO - DAG(s) dict_keys(['ETL']) retrieved from /opt/airflow/dags/etl.py
[2022-11-12T13:14:29.067+0000] {logging_mixin.py:120} INFO - [2022-11-12T13:14:29.066+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-12T13:14:29.118+0000] {logging_mixin.py:120} INFO - [2022-11-12T13:14:29.118+0000] {dag.py:3340} INFO - Setting next_dagrun for ETL to 2022-11-12T00:00:00+00:00, run_after=2022-11-13T00:00:00+00:00
[2022-11-12T13:14:29.168+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/etl.py took 0.247 seconds
[2022-11-12T13:14:59.383+0000] {processor.py:154} INFO - Started process (PID=513) to work on /opt/airflow/dags/etl.py
[2022-11-12T13:14:59.388+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2022-11-12T13:14:59.393+0000] {logging_mixin.py:120} INFO - [2022-11-12T13:14:59.391+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2022-11-12T13:14:59.438+0000] {processor.py:766} INFO - DAG(s) dict_keys(['ETL']) retrieved from /opt/airflow/dags/etl.py
[2022-11-12T13:14:59.507+0000] {logging_mixin.py:120} INFO - [2022-11-12T13:14:59.506+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-12T13:14:59.573+0000] {logging_mixin.py:120} INFO - [2022-11-12T13:14:59.573+0000] {dag.py:3340} INFO - Setting next_dagrun for ETL to 2022-11-12T00:00:00+00:00, run_after=2022-11-13T00:00:00+00:00
[2022-11-12T13:14:59.616+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/etl.py took 0.245 seconds
[2022-11-12T13:15:29.845+0000] {processor.py:154} INFO - Started process (PID=523) to work on /opt/airflow/dags/etl.py
[2022-11-12T13:15:29.848+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2022-11-12T13:15:29.851+0000] {logging_mixin.py:120} INFO - [2022-11-12T13:15:29.851+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2022-11-12T13:15:29.898+0000] {processor.py:766} INFO - DAG(s) dict_keys(['ETL']) retrieved from /opt/airflow/dags/etl.py
[2022-11-12T13:15:29.991+0000] {logging_mixin.py:120} INFO - [2022-11-12T13:15:29.990+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-12T13:15:30.040+0000] {logging_mixin.py:120} INFO - [2022-11-12T13:15:30.040+0000] {dag.py:3340} INFO - Setting next_dagrun for ETL to 2022-11-12T00:00:00+00:00, run_after=2022-11-13T00:00:00+00:00
[2022-11-12T13:15:30.082+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/etl.py took 0.246 seconds
[2022-11-12T13:16:00.351+0000] {processor.py:154} INFO - Started process (PID=533) to work on /opt/airflow/dags/etl.py
[2022-11-12T13:16:00.353+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2022-11-12T13:16:00.357+0000] {logging_mixin.py:120} INFO - [2022-11-12T13:16:00.356+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2022-11-12T13:16:00.415+0000] {processor.py:766} INFO - DAG(s) dict_keys(['ETL']) retrieved from /opt/airflow/dags/etl.py
[2022-11-12T13:16:00.488+0000] {logging_mixin.py:120} INFO - [2022-11-12T13:16:00.488+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-12T13:16:00.534+0000] {logging_mixin.py:120} INFO - [2022-11-12T13:16:00.534+0000] {dag.py:3340} INFO - Setting next_dagrun for ETL to 2022-11-12T00:00:00+00:00, run_after=2022-11-13T00:00:00+00:00
[2022-11-12T13:16:00.570+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/etl.py took 0.224 seconds
[2022-11-12T13:16:30.849+0000] {processor.py:154} INFO - Started process (PID=543) to work on /opt/airflow/dags/etl.py
[2022-11-12T13:16:30.853+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2022-11-12T13:16:30.856+0000] {logging_mixin.py:120} INFO - [2022-11-12T13:16:30.856+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2022-11-12T13:16:30.907+0000] {processor.py:766} INFO - DAG(s) dict_keys(['ETL']) retrieved from /opt/airflow/dags/etl.py
[2022-11-12T13:16:30.978+0000] {logging_mixin.py:120} INFO - [2022-11-12T13:16:30.978+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-12T13:16:31.020+0000] {logging_mixin.py:120} INFO - [2022-11-12T13:16:31.020+0000] {dag.py:3340} INFO - Setting next_dagrun for ETL to 2022-11-12T00:00:00+00:00, run_after=2022-11-13T00:00:00+00:00
[2022-11-12T13:16:31.054+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/etl.py took 0.210 seconds
[2022-11-12T13:17:01.264+0000] {processor.py:154} INFO - Started process (PID=553) to work on /opt/airflow/dags/etl.py
[2022-11-12T13:17:01.269+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2022-11-12T13:17:01.273+0000] {logging_mixin.py:120} INFO - [2022-11-12T13:17:01.272+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2022-11-12T13:17:01.326+0000] {processor.py:766} INFO - DAG(s) dict_keys(['ETL']) retrieved from /opt/airflow/dags/etl.py
[2022-11-12T13:17:01.405+0000] {logging_mixin.py:120} INFO - [2022-11-12T13:17:01.405+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-12T13:17:01.461+0000] {logging_mixin.py:120} INFO - [2022-11-12T13:17:01.460+0000] {dag.py:3340} INFO - Setting next_dagrun for ETL to 2022-11-12T00:00:00+00:00, run_after=2022-11-13T00:00:00+00:00
[2022-11-12T13:17:01.498+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/etl.py took 0.240 seconds
[2022-11-12T13:17:31.790+0000] {processor.py:154} INFO - Started process (PID=563) to work on /opt/airflow/dags/etl.py
[2022-11-12T13:17:31.792+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2022-11-12T13:17:31.798+0000] {logging_mixin.py:120} INFO - [2022-11-12T13:17:31.798+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2022-11-12T13:17:31.840+0000] {processor.py:766} INFO - DAG(s) dict_keys(['ETL']) retrieved from /opt/airflow/dags/etl.py
[2022-11-12T13:17:31.908+0000] {logging_mixin.py:120} INFO - [2022-11-12T13:17:31.907+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-12T13:17:31.951+0000] {logging_mixin.py:120} INFO - [2022-11-12T13:17:31.951+0000] {dag.py:3340} INFO - Setting next_dagrun for ETL to 2022-11-12T00:00:00+00:00, run_after=2022-11-13T00:00:00+00:00
[2022-11-12T13:17:31.982+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/etl.py took 0.201 seconds
[2022-11-12T13:18:02.296+0000] {processor.py:154} INFO - Started process (PID=573) to work on /opt/airflow/dags/etl.py
[2022-11-12T13:18:02.299+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2022-11-12T13:18:02.302+0000] {logging_mixin.py:120} INFO - [2022-11-12T13:18:02.302+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2022-11-12T13:18:02.366+0000] {processor.py:766} INFO - DAG(s) dict_keys(['ETL']) retrieved from /opt/airflow/dags/etl.py
[2022-11-12T13:18:02.462+0000] {logging_mixin.py:120} INFO - [2022-11-12T13:18:02.462+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-12T13:18:02.510+0000] {logging_mixin.py:120} INFO - [2022-11-12T13:18:02.510+0000] {dag.py:3340} INFO - Setting next_dagrun for ETL to 2022-11-12T00:00:00+00:00, run_after=2022-11-13T00:00:00+00:00
[2022-11-12T13:18:02.543+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/etl.py took 0.265 seconds
[2022-11-12T13:18:32.809+0000] {processor.py:154} INFO - Started process (PID=583) to work on /opt/airflow/dags/etl.py
[2022-11-12T13:18:32.812+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2022-11-12T13:18:32.819+0000] {logging_mixin.py:120} INFO - [2022-11-12T13:18:32.818+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2022-11-12T13:18:32.880+0000] {processor.py:766} INFO - DAG(s) dict_keys(['ETL']) retrieved from /opt/airflow/dags/etl.py
[2022-11-12T13:18:33.030+0000] {logging_mixin.py:120} INFO - [2022-11-12T13:18:33.029+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-12T13:18:33.122+0000] {logging_mixin.py:120} INFO - [2022-11-12T13:18:33.122+0000] {dag.py:3340} INFO - Setting next_dagrun for ETL to 2022-11-12T00:00:00+00:00, run_after=2022-11-13T00:00:00+00:00
[2022-11-12T13:18:33.165+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/etl.py took 0.373 seconds
[2022-11-12T13:19:03.696+0000] {processor.py:154} INFO - Started process (PID=593) to work on /opt/airflow/dags/etl.py
[2022-11-12T13:19:03.705+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2022-11-12T13:19:03.721+0000] {logging_mixin.py:120} INFO - [2022-11-12T13:19:03.721+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2022-11-12T13:19:03.960+0000] {processor.py:766} INFO - DAG(s) dict_keys(['ETL']) retrieved from /opt/airflow/dags/etl.py
[2022-11-12T13:19:04.105+0000] {logging_mixin.py:120} INFO - [2022-11-12T13:19:04.105+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-12T13:19:04.212+0000] {logging_mixin.py:120} INFO - [2022-11-12T13:19:04.211+0000] {dag.py:3340} INFO - Setting next_dagrun for ETL to 2022-11-12T00:00:00+00:00, run_after=2022-11-13T00:00:00+00:00
[2022-11-12T13:19:04.439+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/etl.py took 0.758 seconds
[2022-11-12T13:19:34.785+0000] {processor.py:154} INFO - Started process (PID=603) to work on /opt/airflow/dags/etl.py
[2022-11-12T13:19:34.788+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2022-11-12T13:19:34.791+0000] {logging_mixin.py:120} INFO - [2022-11-12T13:19:34.791+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2022-11-12T13:19:34.846+0000] {processor.py:766} INFO - DAG(s) dict_keys(['ETL']) retrieved from /opt/airflow/dags/etl.py
[2022-11-12T13:19:34.933+0000] {logging_mixin.py:120} INFO - [2022-11-12T13:19:34.933+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-12T13:19:35.007+0000] {logging_mixin.py:120} INFO - [2022-11-12T13:19:35.007+0000] {dag.py:3340} INFO - Setting next_dagrun for ETL to 2022-11-12T00:00:00+00:00, run_after=2022-11-13T00:00:00+00:00
[2022-11-12T13:19:35.046+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/etl.py took 0.268 seconds
[2022-11-12T13:20:05.468+0000] {processor.py:154} INFO - Started process (PID=613) to work on /opt/airflow/dags/etl.py
[2022-11-12T13:20:05.475+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2022-11-12T13:20:05.481+0000] {logging_mixin.py:120} INFO - [2022-11-12T13:20:05.478+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2022-11-12T13:20:05.615+0000] {processor.py:766} INFO - DAG(s) dict_keys(['ETL']) retrieved from /opt/airflow/dags/etl.py
[2022-11-12T13:20:05.747+0000] {logging_mixin.py:120} INFO - [2022-11-12T13:20:05.747+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-12T13:20:05.831+0000] {logging_mixin.py:120} INFO - [2022-11-12T13:20:05.831+0000] {dag.py:3340} INFO - Setting next_dagrun for ETL to 2022-11-12T00:00:00+00:00, run_after=2022-11-13T00:00:00+00:00
[2022-11-12T13:20:05.944+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/etl.py took 0.494 seconds
[2022-11-12T13:20:36.225+0000] {processor.py:154} INFO - Started process (PID=623) to work on /opt/airflow/dags/etl.py
[2022-11-12T13:20:36.230+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2022-11-12T13:20:36.233+0000] {logging_mixin.py:120} INFO - [2022-11-12T13:20:36.233+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2022-11-12T13:20:36.288+0000] {processor.py:766} INFO - DAG(s) dict_keys(['ETL']) retrieved from /opt/airflow/dags/etl.py
[2022-11-12T13:20:36.360+0000] {logging_mixin.py:120} INFO - [2022-11-12T13:20:36.360+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-12T13:20:36.424+0000] {logging_mixin.py:120} INFO - [2022-11-12T13:20:36.424+0000] {dag.py:3340} INFO - Setting next_dagrun for ETL to 2022-11-12T00:00:00+00:00, run_after=2022-11-13T00:00:00+00:00
[2022-11-12T13:20:36.476+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/etl.py took 0.262 seconds
[2022-11-12T13:21:06.739+0000] {processor.py:154} INFO - Started process (PID=633) to work on /opt/airflow/dags/etl.py
[2022-11-12T13:21:06.745+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2022-11-12T13:21:06.748+0000] {logging_mixin.py:120} INFO - [2022-11-12T13:21:06.747+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2022-11-12T13:21:06.795+0000] {processor.py:766} INFO - DAG(s) dict_keys(['ETL']) retrieved from /opt/airflow/dags/etl.py
[2022-11-12T13:21:06.897+0000] {logging_mixin.py:120} INFO - [2022-11-12T13:21:06.897+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-12T13:21:06.948+0000] {logging_mixin.py:120} INFO - [2022-11-12T13:21:06.948+0000] {dag.py:3340} INFO - Setting next_dagrun for ETL to 2022-11-12T00:00:00+00:00, run_after=2022-11-13T00:00:00+00:00
[2022-11-12T13:21:06.984+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/etl.py took 0.258 seconds
[2022-11-12T13:21:37.368+0000] {processor.py:154} INFO - Started process (PID=643) to work on /opt/airflow/dags/etl.py
[2022-11-12T13:21:37.371+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2022-11-12T13:21:37.377+0000] {logging_mixin.py:120} INFO - [2022-11-12T13:21:37.377+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2022-11-12T13:21:37.443+0000] {processor.py:766} INFO - DAG(s) dict_keys(['ETL']) retrieved from /opt/airflow/dags/etl.py
[2022-11-12T13:21:37.545+0000] {logging_mixin.py:120} INFO - [2022-11-12T13:21:37.545+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-12T13:21:37.598+0000] {logging_mixin.py:120} INFO - [2022-11-12T13:21:37.598+0000] {dag.py:3340} INFO - Setting next_dagrun for ETL to 2022-11-12T00:00:00+00:00, run_after=2022-11-13T00:00:00+00:00
[2022-11-12T13:21:37.635+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/etl.py took 0.277 seconds
[2022-11-12T13:22:08.151+0000] {processor.py:154} INFO - Started process (PID=653) to work on /opt/airflow/dags/etl.py
[2022-11-12T13:22:08.161+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2022-11-12T13:22:08.165+0000] {logging_mixin.py:120} INFO - [2022-11-12T13:22:08.165+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2022-11-12T13:22:08.289+0000] {processor.py:766} INFO - DAG(s) dict_keys(['ETL']) retrieved from /opt/airflow/dags/etl.py
[2022-11-12T13:22:08.800+0000] {logging_mixin.py:120} INFO - [2022-11-12T13:22:08.800+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-12T13:22:08.927+0000] {logging_mixin.py:120} INFO - [2022-11-12T13:22:08.927+0000] {dag.py:3340} INFO - Setting next_dagrun for ETL to 2022-11-12T00:00:00+00:00, run_after=2022-11-13T00:00:00+00:00
[2022-11-12T13:22:09.009+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/etl.py took 0.864 seconds
[2022-11-12T13:22:39.367+0000] {processor.py:154} INFO - Started process (PID=663) to work on /opt/airflow/dags/etl.py
[2022-11-12T13:22:39.372+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2022-11-12T13:22:39.377+0000] {logging_mixin.py:120} INFO - [2022-11-12T13:22:39.376+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2022-11-12T13:22:39.515+0000] {processor.py:766} INFO - DAG(s) dict_keys(['ETL']) retrieved from /opt/airflow/dags/etl.py
[2022-11-12T13:22:39.691+0000] {logging_mixin.py:120} INFO - [2022-11-12T13:22:39.690+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-12T13:22:39.846+0000] {logging_mixin.py:120} INFO - [2022-11-12T13:22:39.844+0000] {dag.py:3340} INFO - Setting next_dagrun for ETL to 2022-11-12T00:00:00+00:00, run_after=2022-11-13T00:00:00+00:00
[2022-11-12T13:22:39.950+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/etl.py took 0.597 seconds
[2022-11-12T13:23:10.472+0000] {processor.py:154} INFO - Started process (PID=673) to work on /opt/airflow/dags/etl.py
[2022-11-12T13:23:10.478+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2022-11-12T13:23:10.491+0000] {logging_mixin.py:120} INFO - [2022-11-12T13:23:10.490+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2022-11-12T13:23:10.645+0000] {processor.py:766} INFO - DAG(s) dict_keys(['ETL']) retrieved from /opt/airflow/dags/etl.py
[2022-11-12T13:23:10.905+0000] {logging_mixin.py:120} INFO - [2022-11-12T13:23:10.905+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-12T13:23:11.061+0000] {logging_mixin.py:120} INFO - [2022-11-12T13:23:11.061+0000] {dag.py:3340} INFO - Setting next_dagrun for ETL to 2022-11-12T00:00:00+00:00, run_after=2022-11-13T00:00:00+00:00
[2022-11-12T13:23:11.162+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/etl.py took 0.741 seconds
[2022-11-12T13:23:41.584+0000] {processor.py:154} INFO - Started process (PID=683) to work on /opt/airflow/dags/etl.py
[2022-11-12T13:23:41.587+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2022-11-12T13:23:41.589+0000] {logging_mixin.py:120} INFO - [2022-11-12T13:23:41.589+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2022-11-12T13:23:41.645+0000] {processor.py:766} INFO - DAG(s) dict_keys(['ETL']) retrieved from /opt/airflow/dags/etl.py
[2022-11-12T13:23:41.725+0000] {logging_mixin.py:120} INFO - [2022-11-12T13:23:41.725+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-12T13:23:41.791+0000] {logging_mixin.py:120} INFO - [2022-11-12T13:23:41.791+0000] {dag.py:3340} INFO - Setting next_dagrun for ETL to 2022-11-12T00:00:00+00:00, run_after=2022-11-13T00:00:00+00:00
[2022-11-12T13:23:41.848+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/etl.py took 0.269 seconds
[2022-11-12T13:24:12.173+0000] {processor.py:154} INFO - Started process (PID=693) to work on /opt/airflow/dags/etl.py
[2022-11-12T13:24:12.180+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2022-11-12T13:24:12.191+0000] {logging_mixin.py:120} INFO - [2022-11-12T13:24:12.191+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2022-11-12T13:24:12.319+0000] {processor.py:766} INFO - DAG(s) dict_keys(['ETL']) retrieved from /opt/airflow/dags/etl.py
[2022-11-12T13:24:12.482+0000] {logging_mixin.py:120} INFO - [2022-11-12T13:24:12.481+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-12T13:24:12.779+0000] {logging_mixin.py:120} INFO - [2022-11-12T13:24:12.778+0000] {dag.py:3340} INFO - Setting next_dagrun for ETL to 2022-11-12T00:00:00+00:00, run_after=2022-11-13T00:00:00+00:00
[2022-11-12T13:24:12.892+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/etl.py took 0.726 seconds
[2022-11-12T13:24:43.357+0000] {processor.py:154} INFO - Started process (PID=703) to work on /opt/airflow/dags/etl.py
[2022-11-12T13:24:43.372+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2022-11-12T13:24:43.382+0000] {logging_mixin.py:120} INFO - [2022-11-12T13:24:43.379+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2022-11-12T13:24:43.591+0000] {processor.py:766} INFO - DAG(s) dict_keys(['ETL']) retrieved from /opt/airflow/dags/etl.py
[2022-11-12T13:24:43.791+0000] {logging_mixin.py:120} INFO - [2022-11-12T13:24:43.790+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-12T13:24:43.945+0000] {logging_mixin.py:120} INFO - [2022-11-12T13:24:43.945+0000] {dag.py:3340} INFO - Setting next_dagrun for ETL to 2022-11-12T00:00:00+00:00, run_after=2022-11-13T00:00:00+00:00
[2022-11-12T13:24:44.044+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/etl.py took 0.707 seconds
[2022-11-12T13:25:14.404+0000] {processor.py:154} INFO - Started process (PID=713) to work on /opt/airflow/dags/etl.py
[2022-11-12T13:25:14.407+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2022-11-12T13:25:14.411+0000] {logging_mixin.py:120} INFO - [2022-11-12T13:25:14.410+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2022-11-12T13:25:14.469+0000] {processor.py:766} INFO - DAG(s) dict_keys(['ETL']) retrieved from /opt/airflow/dags/etl.py
[2022-11-12T13:25:14.587+0000] {logging_mixin.py:120} INFO - [2022-11-12T13:25:14.587+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-12T13:25:14.631+0000] {logging_mixin.py:120} INFO - [2022-11-12T13:25:14.631+0000] {dag.py:3340} INFO - Setting next_dagrun for ETL to 2022-11-12T00:00:00+00:00, run_after=2022-11-13T00:00:00+00:00
[2022-11-12T13:25:14.667+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/etl.py took 0.271 seconds
[2022-11-12T13:25:45.023+0000] {processor.py:154} INFO - Started process (PID=723) to work on /opt/airflow/dags/etl.py
[2022-11-12T13:25:45.026+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2022-11-12T13:25:45.029+0000] {logging_mixin.py:120} INFO - [2022-11-12T13:25:45.028+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2022-11-12T13:25:45.093+0000] {processor.py:766} INFO - DAG(s) dict_keys(['ETL']) retrieved from /opt/airflow/dags/etl.py
[2022-11-12T13:25:45.164+0000] {logging_mixin.py:120} INFO - [2022-11-12T13:25:45.164+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-12T13:25:45.210+0000] {logging_mixin.py:120} INFO - [2022-11-12T13:25:45.209+0000] {dag.py:3340} INFO - Setting next_dagrun for ETL to 2022-11-12T00:00:00+00:00, run_after=2022-11-13T00:00:00+00:00
[2022-11-12T13:25:45.249+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/etl.py took 0.232 seconds
[2022-11-12T13:26:15.681+0000] {processor.py:154} INFO - Started process (PID=733) to work on /opt/airflow/dags/etl.py
[2022-11-12T13:26:15.683+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2022-11-12T13:26:15.688+0000] {logging_mixin.py:120} INFO - [2022-11-12T13:26:15.687+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2022-11-12T13:26:15.731+0000] {processor.py:766} INFO - DAG(s) dict_keys(['ETL']) retrieved from /opt/airflow/dags/etl.py
[2022-11-12T13:26:15.801+0000] {logging_mixin.py:120} INFO - [2022-11-12T13:26:15.801+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-12T13:26:15.851+0000] {logging_mixin.py:120} INFO - [2022-11-12T13:26:15.851+0000] {dag.py:3340} INFO - Setting next_dagrun for ETL to 2022-11-12T00:00:00+00:00, run_after=2022-11-13T00:00:00+00:00
[2022-11-12T13:26:15.888+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/etl.py took 0.213 seconds
[2022-11-12T13:26:46.180+0000] {processor.py:154} INFO - Started process (PID=743) to work on /opt/airflow/dags/etl.py
[2022-11-12T13:26:46.184+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2022-11-12T13:26:46.187+0000] {logging_mixin.py:120} INFO - [2022-11-12T13:26:46.187+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2022-11-12T13:26:46.234+0000] {processor.py:766} INFO - DAG(s) dict_keys(['ETL']) retrieved from /opt/airflow/dags/etl.py
[2022-11-12T13:26:46.322+0000] {logging_mixin.py:120} INFO - [2022-11-12T13:26:46.322+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-12T13:26:46.389+0000] {logging_mixin.py:120} INFO - [2022-11-12T13:26:46.389+0000] {dag.py:3340} INFO - Setting next_dagrun for ETL to 2022-11-12T00:00:00+00:00, run_after=2022-11-13T00:00:00+00:00
[2022-11-12T13:26:46.420+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/etl.py took 0.250 seconds
[2022-11-12T13:27:16.745+0000] {processor.py:154} INFO - Started process (PID=753) to work on /opt/airflow/dags/etl.py
[2022-11-12T13:27:16.758+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2022-11-12T13:27:16.763+0000] {logging_mixin.py:120} INFO - [2022-11-12T13:27:16.763+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2022-11-12T13:27:16.851+0000] {processor.py:766} INFO - DAG(s) dict_keys(['ETL']) retrieved from /opt/airflow/dags/etl.py
[2022-11-12T13:27:17.071+0000] {logging_mixin.py:120} INFO - [2022-11-12T13:27:17.070+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-12T13:27:17.177+0000] {logging_mixin.py:120} INFO - [2022-11-12T13:27:17.177+0000] {dag.py:3340} INFO - Setting next_dagrun for ETL to 2022-11-12T00:00:00+00:00, run_after=2022-11-13T00:00:00+00:00
[2022-11-12T13:27:17.254+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/etl.py took 0.521 seconds
[2022-11-12T13:27:47.610+0000] {processor.py:154} INFO - Started process (PID=763) to work on /opt/airflow/dags/etl.py
[2022-11-12T13:27:47.616+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2022-11-12T13:27:47.624+0000] {logging_mixin.py:120} INFO - [2022-11-12T13:27:47.621+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2022-11-12T13:27:47.707+0000] {processor.py:766} INFO - DAG(s) dict_keys(['ETL']) retrieved from /opt/airflow/dags/etl.py
[2022-11-12T13:27:47.796+0000] {logging_mixin.py:120} INFO - [2022-11-12T13:27:47.796+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-12T13:27:47.858+0000] {logging_mixin.py:120} INFO - [2022-11-12T13:27:47.858+0000] {dag.py:3340} INFO - Setting next_dagrun for ETL to 2022-11-12T00:00:00+00:00, run_after=2022-11-13T00:00:00+00:00
[2022-11-12T13:27:47.905+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/etl.py took 0.307 seconds
[2022-11-12T13:28:18.280+0000] {processor.py:154} INFO - Started process (PID=773) to work on /opt/airflow/dags/etl.py
[2022-11-12T13:28:18.290+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2022-11-12T13:28:18.300+0000] {logging_mixin.py:120} INFO - [2022-11-12T13:28:18.299+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2022-11-12T13:28:18.379+0000] {processor.py:766} INFO - DAG(s) dict_keys(['ETL']) retrieved from /opt/airflow/dags/etl.py
[2022-11-12T13:28:18.502+0000] {logging_mixin.py:120} INFO - [2022-11-12T13:28:18.501+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-12T13:28:18.571+0000] {logging_mixin.py:120} INFO - [2022-11-12T13:28:18.571+0000] {dag.py:3340} INFO - Setting next_dagrun for ETL to 2022-11-12T00:00:00+00:00, run_after=2022-11-13T00:00:00+00:00
[2022-11-12T13:28:18.635+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/etl.py took 0.367 seconds
[2022-11-12T13:28:48.946+0000] {processor.py:154} INFO - Started process (PID=783) to work on /opt/airflow/dags/etl.py
[2022-11-12T13:28:48.951+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2022-11-12T13:28:48.953+0000] {logging_mixin.py:120} INFO - [2022-11-12T13:28:48.953+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2022-11-12T13:28:49.029+0000] {processor.py:766} INFO - DAG(s) dict_keys(['ETL']) retrieved from /opt/airflow/dags/etl.py
[2022-11-12T13:28:49.113+0000] {logging_mixin.py:120} INFO - [2022-11-12T13:28:49.112+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-12T13:28:49.293+0000] {logging_mixin.py:120} INFO - [2022-11-12T13:28:49.293+0000] {dag.py:3340} INFO - Setting next_dagrun for ETL to 2022-11-12T00:00:00+00:00, run_after=2022-11-13T00:00:00+00:00
[2022-11-12T13:28:49.406+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/etl.py took 0.466 seconds
[2022-11-12T13:29:19.662+0000] {processor.py:154} INFO - Started process (PID=793) to work on /opt/airflow/dags/etl.py
[2022-11-12T13:29:19.665+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2022-11-12T13:29:19.667+0000] {logging_mixin.py:120} INFO - [2022-11-12T13:29:19.667+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2022-11-12T13:29:19.735+0000] {processor.py:766} INFO - DAG(s) dict_keys(['ETL']) retrieved from /opt/airflow/dags/etl.py
[2022-11-12T13:29:19.801+0000] {logging_mixin.py:120} INFO - [2022-11-12T13:29:19.801+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-12T13:29:19.897+0000] {logging_mixin.py:120} INFO - [2022-11-12T13:29:19.897+0000] {dag.py:3340} INFO - Setting next_dagrun for ETL to 2022-11-12T00:00:00+00:00, run_after=2022-11-13T00:00:00+00:00
[2022-11-12T13:29:19.929+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/etl.py took 0.273 seconds
[2022-11-12T13:29:50.196+0000] {processor.py:154} INFO - Started process (PID=803) to work on /opt/airflow/dags/etl.py
[2022-11-12T13:29:50.212+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2022-11-12T13:29:50.217+0000] {logging_mixin.py:120} INFO - [2022-11-12T13:29:50.217+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2022-11-12T13:29:50.266+0000] {processor.py:766} INFO - DAG(s) dict_keys(['ETL']) retrieved from /opt/airflow/dags/etl.py
[2022-11-12T13:29:50.350+0000] {logging_mixin.py:120} INFO - [2022-11-12T13:29:50.350+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-12T13:29:50.404+0000] {logging_mixin.py:120} INFO - [2022-11-12T13:29:50.403+0000] {dag.py:3340} INFO - Setting next_dagrun for ETL to 2022-11-12T00:00:00+00:00, run_after=2022-11-13T00:00:00+00:00
[2022-11-12T13:29:50.460+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/etl.py took 0.271 seconds
[2022-11-12T13:30:20.934+0000] {processor.py:154} INFO - Started process (PID=813) to work on /opt/airflow/dags/etl.py
[2022-11-12T13:30:20.938+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2022-11-12T13:30:20.940+0000] {logging_mixin.py:120} INFO - [2022-11-12T13:30:20.940+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2022-11-12T13:30:21.021+0000] {processor.py:766} INFO - DAG(s) dict_keys(['ETL']) retrieved from /opt/airflow/dags/etl.py
[2022-11-12T13:30:21.104+0000] {logging_mixin.py:120} INFO - [2022-11-12T13:30:21.104+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-12T13:30:21.149+0000] {logging_mixin.py:120} INFO - [2022-11-12T13:30:21.149+0000] {dag.py:3340} INFO - Setting next_dagrun for ETL to 2022-11-12T00:00:00+00:00, run_after=2022-11-13T00:00:00+00:00
[2022-11-12T13:30:21.190+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/etl.py took 0.270 seconds
[2022-11-12T13:30:51.599+0000] {processor.py:154} INFO - Started process (PID=823) to work on /opt/airflow/dags/etl.py
[2022-11-12T13:30:51.601+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2022-11-12T13:30:51.604+0000] {logging_mixin.py:120} INFO - [2022-11-12T13:30:51.603+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2022-11-12T13:30:51.685+0000] {processor.py:766} INFO - DAG(s) dict_keys(['ETL']) retrieved from /opt/airflow/dags/etl.py
[2022-11-12T13:30:51.822+0000] {logging_mixin.py:120} INFO - [2022-11-12T13:30:51.821+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-12T13:30:51.921+0000] {logging_mixin.py:120} INFO - [2022-11-12T13:30:51.921+0000] {dag.py:3340} INFO - Setting next_dagrun for ETL to 2022-11-12T00:00:00+00:00, run_after=2022-11-13T00:00:00+00:00
[2022-11-12T13:30:51.971+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/etl.py took 0.377 seconds
[2022-11-12T13:31:22.487+0000] {processor.py:154} INFO - Started process (PID=833) to work on /opt/airflow/dags/etl.py
[2022-11-12T13:31:22.492+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2022-11-12T13:31:22.496+0000] {logging_mixin.py:120} INFO - [2022-11-12T13:31:22.495+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2022-11-12T13:31:22.594+0000] {processor.py:766} INFO - DAG(s) dict_keys(['ETL']) retrieved from /opt/airflow/dags/etl.py
[2022-11-12T13:31:22.897+0000] {logging_mixin.py:120} INFO - [2022-11-12T13:31:22.896+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-12T13:31:23.148+0000] {logging_mixin.py:120} INFO - [2022-11-12T13:31:23.147+0000] {dag.py:3340} INFO - Setting next_dagrun for ETL to 2022-11-12T00:00:00+00:00, run_after=2022-11-13T00:00:00+00:00
[2022-11-12T13:31:23.250+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/etl.py took 0.775 seconds
[2022-11-12T13:31:53.873+0000] {processor.py:154} INFO - Started process (PID=843) to work on /opt/airflow/dags/etl.py
[2022-11-12T13:31:53.890+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2022-11-12T13:31:53.902+0000] {logging_mixin.py:120} INFO - [2022-11-12T13:31:53.900+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2022-11-12T13:31:53.978+0000] {processor.py:766} INFO - DAG(s) dict_keys(['ETL']) retrieved from /opt/airflow/dags/etl.py
[2022-11-12T13:31:54.087+0000] {logging_mixin.py:120} INFO - [2022-11-12T13:31:54.087+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-12T13:31:54.154+0000] {logging_mixin.py:120} INFO - [2022-11-12T13:31:54.154+0000] {dag.py:3340} INFO - Setting next_dagrun for ETL to 2022-11-12T00:00:00+00:00, run_after=2022-11-13T00:00:00+00:00
[2022-11-12T13:31:54.205+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/etl.py took 0.361 seconds
[2022-11-12T13:32:24.487+0000] {processor.py:154} INFO - Started process (PID=853) to work on /opt/airflow/dags/etl.py
[2022-11-12T13:32:24.489+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2022-11-12T13:32:24.492+0000] {logging_mixin.py:120} INFO - [2022-11-12T13:32:24.492+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2022-11-12T13:32:24.538+0000] {processor.py:766} INFO - DAG(s) dict_keys(['ETL']) retrieved from /opt/airflow/dags/etl.py
[2022-11-12T13:32:24.607+0000] {logging_mixin.py:120} INFO - [2022-11-12T13:32:24.607+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-12T13:32:24.660+0000] {logging_mixin.py:120} INFO - [2022-11-12T13:32:24.659+0000] {dag.py:3340} INFO - Setting next_dagrun for ETL to 2022-11-12T00:00:00+00:00, run_after=2022-11-13T00:00:00+00:00
[2022-11-12T13:32:24.698+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/etl.py took 0.218 seconds
[2022-11-12T13:32:54.957+0000] {processor.py:154} INFO - Started process (PID=863) to work on /opt/airflow/dags/etl.py
[2022-11-12T13:32:54.968+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2022-11-12T13:32:54.975+0000] {logging_mixin.py:120} INFO - [2022-11-12T13:32:54.974+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2022-11-12T13:32:55.057+0000] {processor.py:766} INFO - DAG(s) dict_keys(['ETL']) retrieved from /opt/airflow/dags/etl.py
[2022-11-12T13:32:55.146+0000] {logging_mixin.py:120} INFO - [2022-11-12T13:32:55.146+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-12T13:32:55.197+0000] {logging_mixin.py:120} INFO - [2022-11-12T13:32:55.197+0000] {dag.py:3340} INFO - Setting next_dagrun for ETL to 2022-11-12T00:00:00+00:00, run_after=2022-11-13T00:00:00+00:00
[2022-11-12T13:32:55.280+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/etl.py took 0.332 seconds
[2022-11-12T13:33:20.558+0000] {processor.py:154} INFO - Started process (PID=873) to work on /opt/airflow/dags/etl.py
[2022-11-12T13:33:20.561+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2022-11-12T13:33:20.565+0000] {logging_mixin.py:120} INFO - [2022-11-12T13:33:20.564+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2022-11-12T13:33:20.611+0000] {logging_mixin.py:120} INFO - [2022-11-12T13:33:20.607+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl.py", line 8, in <module>
    from includes import extract
ModuleNotFoundError: No module named 'includes'
[2022-11-12T13:33:20.612+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/etl.py
[2022-11-12T13:33:20.647+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/etl.py took 0.098 seconds
[2022-11-12T13:34:49.483+0000] {processor.py:154} INFO - Started process (PID=175) to work on /opt/airflow/dags/etl.py
[2022-11-12T13:34:49.485+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2022-11-12T13:34:49.487+0000] {logging_mixin.py:120} INFO - [2022-11-12T13:34:49.487+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2022-11-12T13:34:50.865+0000] {logging_mixin.py:120} INFO - Grupo 99 ....>> runing ETL
[2022-11-12T13:34:50.877+0000] {logging_mixin.py:120} INFO - [E]XTRACT DATA
[2022-11-12T13:34:50.878+0000] {logging_mixin.py:120} INFO -   begin Extract >> PAYMENTS
[2022-11-12T13:34:50.883+0000] {logging_mixin.py:120} INFO - Error mientras extracción de datos: [Errno 2] No such file or directory: '/Users/napo/Documents/proyecto/Big Data/BigData/data/payments'
[2022-11-12T13:34:50.886+0000] {logging_mixin.py:120} INFO -   >>end Extract PAYMENTS..
[2022-11-12T13:34:50.888+0000] {logging_mixin.py:120} INFO -   begin Extract >> CHARGEBACKS
[2022-11-12T13:34:50.890+0000] {logging_mixin.py:120} INFO - Error mientras extracción de datos: [Errno 2] No such file or directory: '/Users/napo/Documents/proyecto/Big Data/BigData/data/chargebacks'
[2022-11-12T13:34:50.891+0000] {logging_mixin.py:120} INFO -   >>end Extract CHARGEBACKS..
[2022-11-12T13:34:50.892+0000] {logging_mixin.py:120} INFO - [end] - EXTRACT-DATA
[2022-11-12T13:34:50.894+0000] {logging_mixin.py:120} INFO - >>El tiempo total de ejecucion del script [extract] es:     0.02868199348449707 Segundos
[2022-11-12T13:34:50.914+0000] {logging_mixin.py:120} INFO - [T]RANSFORM DATA
[2022-11-12T13:34:50.917+0000] {logging_mixin.py:120} INFO - Error mientras extracción de datos: (psycopg2.OperationalError) connection to server at "localhost" (127.0.0.1), port 5438 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5438 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2022-11-12T13:34:50.934+0000] {logging_mixin.py:120} INFO - [L]OAD DATA 
[2022-11-12T13:34:50.940+0000] {logging_mixin.py:120} INFO - Error mientras extracción de datos: (psycopg2.OperationalError) connection to server at "localhost" (127.0.0.1), port 5438 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5438 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2022-11-12T13:34:50.962+0000] {logging_mixin.py:120} INFO - [2022-11-12T13:34:50.956+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl.py", line 37, in <module>
    python_callable=extract
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 408, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 162, in __init__
    raise AirflowException('`python_callable` param must be callable')
airflow.exceptions.AirflowException: `python_callable` param must be callable
[2022-11-12T13:34:50.972+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/etl.py
[2022-11-12T13:34:51.050+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/etl.py took 1.577 seconds
[2022-11-12T13:35:21.350+0000] {processor.py:154} INFO - Started process (PID=190) to work on /opt/airflow/dags/etl.py
[2022-11-12T13:35:21.353+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2022-11-12T13:35:21.356+0000] {logging_mixin.py:120} INFO - [2022-11-12T13:35:21.356+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2022-11-12T13:35:22.070+0000] {logging_mixin.py:120} INFO - Grupo 99 ....>> runing ETL
[2022-11-12T13:35:22.072+0000] {logging_mixin.py:120} INFO - [E]XTRACT DATA
[2022-11-12T13:35:22.074+0000] {logging_mixin.py:120} INFO -   begin Extract >> PAYMENTS
[2022-11-12T13:35:22.076+0000] {logging_mixin.py:120} INFO - Error mientras extracción de datos: [Errno 2] No such file or directory: '/Users/napo/Documents/proyecto/Big Data/BigData/data/payments'
[2022-11-12T13:35:22.078+0000] {logging_mixin.py:120} INFO -   >>end Extract PAYMENTS..
[2022-11-12T13:35:22.079+0000] {logging_mixin.py:120} INFO -   begin Extract >> CHARGEBACKS
[2022-11-12T13:35:22.080+0000] {logging_mixin.py:120} INFO - Error mientras extracción de datos: [Errno 2] No such file or directory: '/Users/napo/Documents/proyecto/Big Data/BigData/data/chargebacks'
[2022-11-12T13:35:22.081+0000] {logging_mixin.py:120} INFO -   >>end Extract CHARGEBACKS..
[2022-11-12T13:35:22.082+0000] {logging_mixin.py:120} INFO - [end] - EXTRACT-DATA
[2022-11-12T13:35:22.082+0000] {logging_mixin.py:120} INFO - >>El tiempo total de ejecucion del script [extract] es:     0.011947154998779297 Segundos
[2022-11-12T13:35:22.087+0000] {logging_mixin.py:120} INFO - [T]RANSFORM DATA
[2022-11-12T13:35:22.090+0000] {logging_mixin.py:120} INFO - Error mientras extracción de datos: (psycopg2.OperationalError) connection to server at "localhost" (127.0.0.1), port 5438 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5438 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2022-11-12T13:35:22.096+0000] {logging_mixin.py:120} INFO - [L]OAD DATA 
[2022-11-12T13:35:22.102+0000] {logging_mixin.py:120} INFO - Error mientras extracción de datos: (psycopg2.OperationalError) connection to server at "localhost" (127.0.0.1), port 5438 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5438 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2022-11-12T13:35:22.124+0000] {logging_mixin.py:120} INFO - [2022-11-12T13:35:22.115+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl.py", line 37, in <module>
    python_callable=extract
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 408, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 162, in __init__
    raise AirflowException('`python_callable` param must be callable')
airflow.exceptions.AirflowException: `python_callable` param must be callable
[2022-11-12T13:35:22.127+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/etl.py
[2022-11-12T13:35:22.172+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/etl.py took 0.832 seconds
[2022-11-12T13:35:52.598+0000] {processor.py:154} INFO - Started process (PID=203) to work on /opt/airflow/dags/etl.py
[2022-11-12T13:35:52.601+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2022-11-12T13:35:52.606+0000] {logging_mixin.py:120} INFO - [2022-11-12T13:35:52.605+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2022-11-12T13:35:53.164+0000] {logging_mixin.py:120} INFO - Grupo 99 ....>> runing ETL
[2022-11-12T13:35:53.166+0000] {logging_mixin.py:120} INFO - [E]XTRACT DATA
[2022-11-12T13:35:53.167+0000] {logging_mixin.py:120} INFO -   begin Extract >> PAYMENTS
[2022-11-12T13:35:53.168+0000] {logging_mixin.py:120} INFO - Error mientras extracción de datos: [Errno 2] No such file or directory: '/Users/napo/Documents/proyecto/Big Data/BigData/data/payments'
[2022-11-12T13:35:53.170+0000] {logging_mixin.py:120} INFO -   >>end Extract PAYMENTS..
[2022-11-12T13:35:53.172+0000] {logging_mixin.py:120} INFO -   begin Extract >> CHARGEBACKS
[2022-11-12T13:35:53.173+0000] {logging_mixin.py:120} INFO - Error mientras extracción de datos: [Errno 2] No such file or directory: '/Users/napo/Documents/proyecto/Big Data/BigData/data/chargebacks'
[2022-11-12T13:35:53.174+0000] {logging_mixin.py:120} INFO -   >>end Extract CHARGEBACKS..
[2022-11-12T13:35:53.176+0000] {logging_mixin.py:120} INFO - [end] - EXTRACT-DATA
[2022-11-12T13:35:53.177+0000] {logging_mixin.py:120} INFO - >>El tiempo total de ejecucion del script [extract] es:     0.012910127639770508 Segundos
[2022-11-12T13:35:53.181+0000] {logging_mixin.py:120} INFO - [T]RANSFORM DATA
[2022-11-12T13:35:53.185+0000] {logging_mixin.py:120} INFO - Error mientras extracción de datos: (psycopg2.OperationalError) connection to server at "localhost" (127.0.0.1), port 5438 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5438 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2022-11-12T13:35:53.189+0000] {logging_mixin.py:120} INFO - [L]OAD DATA 
[2022-11-12T13:35:53.193+0000] {logging_mixin.py:120} INFO - Error mientras extracción de datos: (psycopg2.OperationalError) connection to server at "localhost" (127.0.0.1), port 5438 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5438 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2022-11-12T13:35:53.205+0000] {logging_mixin.py:120} INFO - [2022-11-12T13:35:53.201+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl.py", line 37, in <module>
    python_callable=extract
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 408, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 162, in __init__
    raise AirflowException('`python_callable` param must be callable')
airflow.exceptions.AirflowException: `python_callable` param must be callable
[2022-11-12T13:35:53.207+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/etl.py
[2022-11-12T13:35:53.231+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/etl.py took 0.641 seconds
[2022-11-12T13:36:24.173+0000] {processor.py:154} INFO - Started process (PID=214) to work on /opt/airflow/dags/etl.py
[2022-11-12T13:36:24.176+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2022-11-12T13:36:24.179+0000] {logging_mixin.py:120} INFO - [2022-11-12T13:36:24.179+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2022-11-12T13:36:24.840+0000] {logging_mixin.py:120} INFO - Grupo 99 ....>> runing ETL
[2022-11-12T13:36:24.841+0000] {logging_mixin.py:120} INFO - [E]XTRACT DATA
[2022-11-12T13:36:24.843+0000] {logging_mixin.py:120} INFO -   begin Extract >> PAYMENTS
[2022-11-12T13:36:24.844+0000] {logging_mixin.py:120} INFO - Error mientras extracción de datos: [Errno 2] No such file or directory: '/Users/napo/Documents/proyecto/Big Data/BigData/data/payments'
[2022-11-12T13:36:24.846+0000] {logging_mixin.py:120} INFO -   >>end Extract PAYMENTS..
[2022-11-12T13:36:24.848+0000] {logging_mixin.py:120} INFO -   begin Extract >> CHARGEBACKS
[2022-11-12T13:36:24.849+0000] {logging_mixin.py:120} INFO - Error mientras extracción de datos: [Errno 2] No such file or directory: '/Users/napo/Documents/proyecto/Big Data/BigData/data/chargebacks'
[2022-11-12T13:36:24.850+0000] {logging_mixin.py:120} INFO -   >>end Extract CHARGEBACKS..
[2022-11-12T13:36:24.851+0000] {logging_mixin.py:120} INFO - [end] - EXTRACT-DATA
[2022-11-12T13:36:24.852+0000] {logging_mixin.py:120} INFO - >>El tiempo total de ejecucion del script [extract] es:     0.011574745178222656 Segundos
[2022-11-12T13:36:24.857+0000] {logging_mixin.py:120} INFO - [T]RANSFORM DATA
[2022-11-12T13:36:24.860+0000] {logging_mixin.py:120} INFO - Error mientras extracción de datos: (psycopg2.OperationalError) connection to server at "localhost" (127.0.0.1), port 5438 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5438 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2022-11-12T13:36:24.863+0000] {logging_mixin.py:120} INFO - [L]OAD DATA 
[2022-11-12T13:36:24.866+0000] {logging_mixin.py:120} INFO - Error mientras extracción de datos: (psycopg2.OperationalError) connection to server at "localhost" (127.0.0.1), port 5438 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5438 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2022-11-12T13:36:24.878+0000] {logging_mixin.py:120} INFO - [2022-11-12T13:36:24.874+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl.py", line 37, in <module>
    python_callable=extract
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 408, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 162, in __init__
    raise AirflowException('`python_callable` param must be callable')
airflow.exceptions.AirflowException: `python_callable` param must be callable
[2022-11-12T13:36:24.880+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/etl.py
[2022-11-12T13:36:24.911+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/etl.py took 0.748 seconds
[2022-11-12T13:36:55.536+0000] {processor.py:154} INFO - Started process (PID=225) to work on /opt/airflow/dags/etl.py
[2022-11-12T13:36:55.548+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2022-11-12T13:36:55.551+0000] {logging_mixin.py:120} INFO - [2022-11-12T13:36:55.550+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2022-11-12T13:36:56.214+0000] {logging_mixin.py:120} INFO - Grupo 99 ....>> runing ETL
[2022-11-12T13:36:56.215+0000] {logging_mixin.py:120} INFO - [E]XTRACT DATA
[2022-11-12T13:36:56.216+0000] {logging_mixin.py:120} INFO -   begin Extract >> PAYMENTS
[2022-11-12T13:36:56.218+0000] {logging_mixin.py:120} INFO - Error mientras extracción de datos: [Errno 2] No such file or directory: '/Users/napo/Documents/proyecto/Big Data/BigData/data/payments'
[2022-11-12T13:36:56.219+0000] {logging_mixin.py:120} INFO -   >>end Extract PAYMENTS..
[2022-11-12T13:36:56.220+0000] {logging_mixin.py:120} INFO -   begin Extract >> CHARGEBACKS
[2022-11-12T13:36:56.221+0000] {logging_mixin.py:120} INFO - Error mientras extracción de datos: [Errno 2] No such file or directory: '/Users/napo/Documents/proyecto/Big Data/BigData/data/chargebacks'
[2022-11-12T13:36:56.223+0000] {logging_mixin.py:120} INFO -   >>end Extract CHARGEBACKS..
[2022-11-12T13:36:56.224+0000] {logging_mixin.py:120} INFO - [end] - EXTRACT-DATA
[2022-11-12T13:36:56.225+0000] {logging_mixin.py:120} INFO - >>El tiempo total de ejecucion del script [extract] es:     0.010363101959228516 Segundos
[2022-11-12T13:36:56.227+0000] {logging_mixin.py:120} INFO - [T]RANSFORM DATA
[2022-11-12T13:36:56.230+0000] {logging_mixin.py:120} INFO - Error mientras extracción de datos: (psycopg2.OperationalError) connection to server at "localhost" (127.0.0.1), port 5438 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5438 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2022-11-12T13:36:56.233+0000] {logging_mixin.py:120} INFO - [L]OAD DATA 
[2022-11-12T13:36:56.235+0000] {logging_mixin.py:120} INFO - Error mientras extracción de datos: (psycopg2.OperationalError) connection to server at "localhost" (127.0.0.1), port 5438 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5438 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2022-11-12T13:36:56.245+0000] {logging_mixin.py:120} INFO - [2022-11-12T13:36:56.241+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl.py", line 37, in <module>
    python_callable=extract
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 408, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 162, in __init__
    raise AirflowException('`python_callable` param must be callable')
airflow.exceptions.AirflowException: `python_callable` param must be callable
[2022-11-12T13:36:56.246+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/etl.py
[2022-11-12T13:36:56.273+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/etl.py took 0.753 seconds
[2022-11-12T13:37:26.582+0000] {processor.py:154} INFO - Started process (PID=236) to work on /opt/airflow/dags/etl.py
[2022-11-12T13:37:26.585+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2022-11-12T13:37:26.587+0000] {logging_mixin.py:120} INFO - [2022-11-12T13:37:26.587+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2022-11-12T13:37:27.180+0000] {logging_mixin.py:120} INFO - Grupo 99 ....>> runing ETL
[2022-11-12T13:37:27.181+0000] {logging_mixin.py:120} INFO - [E]XTRACT DATA
[2022-11-12T13:37:27.183+0000] {logging_mixin.py:120} INFO -   begin Extract >> PAYMENTS
[2022-11-12T13:37:27.184+0000] {logging_mixin.py:120} INFO - Error mientras extracción de datos: [Errno 2] No such file or directory: '/Users/napo/Documents/proyecto/Big Data/BigData/data/payments'
[2022-11-12T13:37:27.185+0000] {logging_mixin.py:120} INFO -   >>end Extract PAYMENTS..
[2022-11-12T13:37:27.186+0000] {logging_mixin.py:120} INFO -   begin Extract >> CHARGEBACKS
[2022-11-12T13:37:27.188+0000] {logging_mixin.py:120} INFO - Error mientras extracción de datos: [Errno 2] No such file or directory: '/Users/napo/Documents/proyecto/Big Data/BigData/data/chargebacks'
[2022-11-12T13:37:27.192+0000] {logging_mixin.py:120} INFO -   >>end Extract CHARGEBACKS..
[2022-11-12T13:37:27.193+0000] {logging_mixin.py:120} INFO - [end] - EXTRACT-DATA
[2022-11-12T13:37:27.195+0000] {logging_mixin.py:120} INFO - >>El tiempo total de ejecucion del script [extract] es:     0.014874935150146484 Segundos
[2022-11-12T13:37:27.198+0000] {logging_mixin.py:120} INFO - [T]RANSFORM DATA
[2022-11-12T13:37:27.201+0000] {logging_mixin.py:120} INFO - Error mientras extracción de datos: (psycopg2.OperationalError) connection to server at "localhost" (127.0.0.1), port 5438 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5438 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2022-11-12T13:37:27.205+0000] {logging_mixin.py:120} INFO - [L]OAD DATA 
[2022-11-12T13:37:27.210+0000] {logging_mixin.py:120} INFO - Error mientras extracción de datos: (psycopg2.OperationalError) connection to server at "localhost" (127.0.0.1), port 5438 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5438 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2022-11-12T13:37:27.220+0000] {logging_mixin.py:120} INFO - [2022-11-12T13:37:27.216+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl.py", line 37, in <module>
    python_callable=extract
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 408, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 162, in __init__
    raise AirflowException('`python_callable` param must be callable')
airflow.exceptions.AirflowException: `python_callable` param must be callable
[2022-11-12T13:37:27.223+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/etl.py
[2022-11-12T13:37:27.253+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/etl.py took 0.677 seconds
[2022-11-12T13:37:57.849+0000] {processor.py:154} INFO - Started process (PID=247) to work on /opt/airflow/dags/etl.py
[2022-11-12T13:37:57.853+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2022-11-12T13:37:57.858+0000] {logging_mixin.py:120} INFO - [2022-11-12T13:37:57.857+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2022-11-12T13:37:58.219+0000] {logging_mixin.py:120} INFO - Grupo 99 ....>> runing ETL
[2022-11-12T13:37:58.221+0000] {logging_mixin.py:120} INFO - [E]XTRACT DATA
[2022-11-12T13:37:58.224+0000] {logging_mixin.py:120} INFO -   begin Extract >> PAYMENTS
[2022-11-12T13:37:58.226+0000] {logging_mixin.py:120} INFO - Error mientras extracción de datos: [Errno 2] No such file or directory: '/Users/napo/Documents/proyecto/Big Data/BigData/data/payments'
[2022-11-12T13:37:58.227+0000] {logging_mixin.py:120} INFO -   >>end Extract PAYMENTS..
[2022-11-12T13:37:58.228+0000] {logging_mixin.py:120} INFO -   begin Extract >> CHARGEBACKS
[2022-11-12T13:37:58.229+0000] {logging_mixin.py:120} INFO - Error mientras extracción de datos: [Errno 2] No such file or directory: '/Users/napo/Documents/proyecto/Big Data/BigData/data/chargebacks'
[2022-11-12T13:37:58.229+0000] {logging_mixin.py:120} INFO -   >>end Extract CHARGEBACKS..
[2022-11-12T13:37:58.231+0000] {logging_mixin.py:120} INFO - [end] - EXTRACT-DATA
[2022-11-12T13:37:58.232+0000] {logging_mixin.py:120} INFO - >>El tiempo total de ejecucion del script [extract] es:     0.012524604797363281 Segundos
[2022-11-12T13:37:58.236+0000] {logging_mixin.py:120} INFO - [T]RANSFORM DATA
[2022-11-12T13:37:58.241+0000] {logging_mixin.py:120} INFO - Error mientras extracción de datos: (psycopg2.OperationalError) connection to server at "localhost" (127.0.0.1), port 5438 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5438 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2022-11-12T13:37:58.244+0000] {logging_mixin.py:120} INFO - [L]OAD DATA 
[2022-11-12T13:37:58.247+0000] {logging_mixin.py:120} INFO - Error mientras extracción de datos: (psycopg2.OperationalError) connection to server at "localhost" (127.0.0.1), port 5438 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5438 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2022-11-12T13:37:58.261+0000] {logging_mixin.py:120} INFO - [2022-11-12T13:37:58.258+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl.py", line 37, in <module>
    python_callable=extract
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 408, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 162, in __init__
    raise AirflowException('`python_callable` param must be callable')
airflow.exceptions.AirflowException: `python_callable` param must be callable
[2022-11-12T13:37:58.263+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/etl.py
[2022-11-12T13:37:58.322+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/etl.py took 0.478 seconds
[2022-11-12T13:38:28.475+0000] {processor.py:154} INFO - Started process (PID=258) to work on /opt/airflow/dags/etl.py
[2022-11-12T13:38:28.479+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2022-11-12T13:38:28.483+0000] {logging_mixin.py:120} INFO - [2022-11-12T13:38:28.482+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2022-11-12T13:38:28.888+0000] {logging_mixin.py:120} INFO - Grupo 99 ....>> runing ETL
[2022-11-12T13:38:28.890+0000] {logging_mixin.py:120} INFO - [E]XTRACT DATA
[2022-11-12T13:38:28.891+0000] {logging_mixin.py:120} INFO -   begin Extract >> PAYMENTS
[2022-11-12T13:38:28.893+0000] {logging_mixin.py:120} INFO - Error mientras extracción de datos: [Errno 2] No such file or directory: '/Users/napo/Documents/proyecto/Big Data/BigData/data/payments'
[2022-11-12T13:38:28.894+0000] {logging_mixin.py:120} INFO -   >>end Extract PAYMENTS..
[2022-11-12T13:38:28.895+0000] {logging_mixin.py:120} INFO -   begin Extract >> CHARGEBACKS
[2022-11-12T13:38:28.896+0000] {logging_mixin.py:120} INFO - Error mientras extracción de datos: [Errno 2] No such file or directory: '/Users/napo/Documents/proyecto/Big Data/BigData/data/chargebacks'
[2022-11-12T13:38:28.897+0000] {logging_mixin.py:120} INFO -   >>end Extract CHARGEBACKS..
[2022-11-12T13:38:28.898+0000] {logging_mixin.py:120} INFO - [end] - EXTRACT-DATA
[2022-11-12T13:38:28.899+0000] {logging_mixin.py:120} INFO - >>El tiempo total de ejecucion del script [extract] es:     0.011158227920532227 Segundos
[2022-11-12T13:38:28.906+0000] {logging_mixin.py:120} INFO - [T]RANSFORM DATA
[2022-11-12T13:38:28.911+0000] {logging_mixin.py:120} INFO - Error mientras extracción de datos: (psycopg2.OperationalError) connection to server at "localhost" (127.0.0.1), port 5438 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5438 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2022-11-12T13:38:28.915+0000] {logging_mixin.py:120} INFO - [L]OAD DATA 
[2022-11-12T13:38:28.918+0000] {logging_mixin.py:120} INFO - Error mientras extracción de datos: (psycopg2.OperationalError) connection to server at "localhost" (127.0.0.1), port 5438 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5438 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2022-11-12T13:38:28.933+0000] {logging_mixin.py:120} INFO - [2022-11-12T13:38:28.929+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl.py", line 37, in <module>
    python_callable=extract
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 408, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 162, in __init__
    raise AirflowException('`python_callable` param must be callable')
airflow.exceptions.AirflowException: `python_callable` param must be callable
[2022-11-12T13:38:28.934+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/etl.py
[2022-11-12T13:38:28.980+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/etl.py took 0.514 seconds
[2022-11-12T13:38:59.779+0000] {processor.py:154} INFO - Started process (PID=269) to work on /opt/airflow/dags/etl.py
[2022-11-12T13:38:59.783+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2022-11-12T13:38:59.785+0000] {logging_mixin.py:120} INFO - [2022-11-12T13:38:59.785+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2022-11-12T13:39:00.123+0000] {logging_mixin.py:120} INFO - Grupo 99 ....>> runing ETL
[2022-11-12T13:39:00.124+0000] {logging_mixin.py:120} INFO - [E]XTRACT DATA
[2022-11-12T13:39:00.125+0000] {logging_mixin.py:120} INFO -   begin Extract >> PAYMENTS
[2022-11-12T13:39:00.126+0000] {logging_mixin.py:120} INFO - Error mientras extracción de datos: [Errno 2] No such file or directory: '/Users/napo/Documents/proyecto/Big Data/BigData/data/payments'
[2022-11-12T13:39:00.127+0000] {logging_mixin.py:120} INFO -   >>end Extract PAYMENTS..
[2022-11-12T13:39:00.128+0000] {logging_mixin.py:120} INFO -   begin Extract >> CHARGEBACKS
[2022-11-12T13:39:00.129+0000] {logging_mixin.py:120} INFO - Error mientras extracción de datos: [Errno 2] No such file or directory: '/Users/napo/Documents/proyecto/Big Data/BigData/data/chargebacks'
[2022-11-12T13:39:00.130+0000] {logging_mixin.py:120} INFO -   >>end Extract CHARGEBACKS..
[2022-11-12T13:39:00.131+0000] {logging_mixin.py:120} INFO - [end] - EXTRACT-DATA
[2022-11-12T13:39:00.132+0000] {logging_mixin.py:120} INFO - >>El tiempo total de ejecucion del script [extract] es:     0.00908660888671875 Segundos
[2022-11-12T13:39:00.135+0000] {logging_mixin.py:120} INFO - [T]RANSFORM DATA
[2022-11-12T13:39:00.138+0000] {logging_mixin.py:120} INFO - Error mientras extracción de datos: (psycopg2.OperationalError) connection to server at "localhost" (127.0.0.1), port 5438 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5438 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2022-11-12T13:39:00.141+0000] {logging_mixin.py:120} INFO - [L]OAD DATA 
[2022-11-12T13:39:00.144+0000] {logging_mixin.py:120} INFO - Error mientras extracción de datos: (psycopg2.OperationalError) connection to server at "localhost" (127.0.0.1), port 5438 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5438 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2022-11-12T13:39:00.155+0000] {logging_mixin.py:120} INFO - [2022-11-12T13:39:00.151+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl.py", line 37, in <module>
    python_callable=extract
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 408, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 162, in __init__
    raise AirflowException('`python_callable` param must be callable')
airflow.exceptions.AirflowException: `python_callable` param must be callable
[2022-11-12T13:39:00.157+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/etl.py
[2022-11-12T13:39:00.182+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/etl.py took 0.411 seconds
[2022-11-12T13:39:30.513+0000] {processor.py:154} INFO - Started process (PID=280) to work on /opt/airflow/dags/etl.py
[2022-11-12T13:39:30.524+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2022-11-12T13:39:30.527+0000] {logging_mixin.py:120} INFO - [2022-11-12T13:39:30.526+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2022-11-12T13:39:30.923+0000] {logging_mixin.py:120} INFO - Grupo 99 ....>> runing ETL
[2022-11-12T13:39:30.924+0000] {logging_mixin.py:120} INFO - [E]XTRACT DATA
[2022-11-12T13:39:30.926+0000] {logging_mixin.py:120} INFO -   begin Extract >> PAYMENTS
[2022-11-12T13:39:30.927+0000] {logging_mixin.py:120} INFO - Error mientras extracción de datos: [Errno 2] No such file or directory: '/Users/napo/Documents/proyecto/Big Data/BigData/data/payments'
[2022-11-12T13:39:30.929+0000] {logging_mixin.py:120} INFO -   >>end Extract PAYMENTS..
[2022-11-12T13:39:30.932+0000] {logging_mixin.py:120} INFO -   begin Extract >> CHARGEBACKS
[2022-11-12T13:39:30.934+0000] {logging_mixin.py:120} INFO - Error mientras extracción de datos: [Errno 2] No such file or directory: '/Users/napo/Documents/proyecto/Big Data/BigData/data/chargebacks'
[2022-11-12T13:39:30.937+0000] {logging_mixin.py:120} INFO -   >>end Extract CHARGEBACKS..
[2022-11-12T13:39:30.938+0000] {logging_mixin.py:120} INFO - [end] - EXTRACT-DATA
[2022-11-12T13:39:30.939+0000] {logging_mixin.py:120} INFO - >>El tiempo total de ejecucion del script [extract] es:     0.016022205352783203 Segundos
[2022-11-12T13:39:30.942+0000] {logging_mixin.py:120} INFO - [T]RANSFORM DATA
[2022-11-12T13:39:30.946+0000] {logging_mixin.py:120} INFO - Error mientras extracción de datos: (psycopg2.OperationalError) connection to server at "localhost" (127.0.0.1), port 5438 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5438 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2022-11-12T13:39:30.954+0000] {logging_mixin.py:120} INFO - [L]OAD DATA 
[2022-11-12T13:39:30.957+0000] {logging_mixin.py:120} INFO - Error mientras extracción de datos: (psycopg2.OperationalError) connection to server at "localhost" (127.0.0.1), port 5438 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5438 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2022-11-12T13:39:30.969+0000] {logging_mixin.py:120} INFO - [2022-11-12T13:39:30.965+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl.py", line 37, in <module>
    python_callable=extract
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 408, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 162, in __init__
    raise AirflowException('`python_callable` param must be callable')
airflow.exceptions.AirflowException: `python_callable` param must be callable
[2022-11-12T13:39:30.970+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/etl.py
[2022-11-12T13:39:30.999+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/etl.py took 0.492 seconds
[2022-11-12T13:40:01.296+0000] {processor.py:154} INFO - Started process (PID=291) to work on /opt/airflow/dags/etl.py
[2022-11-12T13:40:01.300+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2022-11-12T13:40:01.304+0000] {logging_mixin.py:120} INFO - [2022-11-12T13:40:01.303+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2022-11-12T13:40:02.673+0000] {logging_mixin.py:120} INFO - Grupo 99 ....>> runing ETL
[2022-11-12T13:40:02.676+0000] {logging_mixin.py:120} INFO - [E]XTRACT DATA
[2022-11-12T13:40:02.678+0000] {logging_mixin.py:120} INFO -   begin Extract >> PAYMENTS
[2022-11-12T13:40:02.680+0000] {logging_mixin.py:120} INFO - Error mientras extracción de datos: [Errno 2] No such file or directory: '/Users/napo/Documents/proyecto/Big Data/BigData/data/payments'
[2022-11-12T13:40:02.687+0000] {logging_mixin.py:120} INFO -   >>end Extract PAYMENTS..
[2022-11-12T13:40:02.689+0000] {logging_mixin.py:120} INFO -   begin Extract >> CHARGEBACKS
[2022-11-12T13:40:02.692+0000] {logging_mixin.py:120} INFO - Error mientras extracción de datos: [Errno 2] No such file or directory: '/Users/napo/Documents/proyecto/Big Data/BigData/data/chargebacks'
[2022-11-12T13:40:02.695+0000] {logging_mixin.py:120} INFO -   >>end Extract CHARGEBACKS..
[2022-11-12T13:40:02.706+0000] {logging_mixin.py:120} INFO - [end] - EXTRACT-DATA
[2022-11-12T13:40:02.710+0000] {logging_mixin.py:120} INFO - >>El tiempo total de ejecucion del script [extract] es:     0.03700423240661621 Segundos
[2022-11-12T13:40:02.726+0000] {logging_mixin.py:120} INFO - [T]RANSFORM DATA
[2022-11-12T13:40:02.732+0000] {logging_mixin.py:120} INFO - Error mientras extracción de datos: (psycopg2.OperationalError) connection to server at "localhost" (127.0.0.1), port 5438 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5438 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2022-11-12T13:40:02.761+0000] {logging_mixin.py:120} INFO - [L]OAD DATA 
[2022-11-12T13:40:02.769+0000] {logging_mixin.py:120} INFO - Error mientras extracción de datos: (psycopg2.OperationalError) connection to server at "localhost" (127.0.0.1), port 5438 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5438 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2022-11-12T13:40:02.848+0000] {logging_mixin.py:120} INFO - [2022-11-12T13:40:02.796+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl.py", line 37, in <module>
    python_callable=extract
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 408, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 162, in __init__
    raise AirflowException('`python_callable` param must be callable')
airflow.exceptions.AirflowException: `python_callable` param must be callable
[2022-11-12T13:40:02.856+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/etl.py
[2022-11-12T13:40:03.059+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/etl.py took 1.752 seconds
[2022-11-12T13:40:34.035+0000] {processor.py:154} INFO - Started process (PID=302) to work on /opt/airflow/dags/etl.py
[2022-11-12T13:40:34.040+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2022-11-12T13:40:34.044+0000] {logging_mixin.py:120} INFO - [2022-11-12T13:40:34.044+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2022-11-12T13:40:34.539+0000] {logging_mixin.py:120} INFO - Grupo 99 ....>> runing ETL
[2022-11-12T13:40:34.540+0000] {logging_mixin.py:120} INFO - [E]XTRACT DATA
[2022-11-12T13:40:34.541+0000] {logging_mixin.py:120} INFO -   begin Extract >> PAYMENTS
[2022-11-12T13:40:34.542+0000] {logging_mixin.py:120} INFO - Error mientras extracción de datos: [Errno 2] No such file or directory: '/Users/napo/Documents/proyecto/Big Data/BigData/data/payments'
[2022-11-12T13:40:34.543+0000] {logging_mixin.py:120} INFO -   >>end Extract PAYMENTS..
[2022-11-12T13:40:34.544+0000] {logging_mixin.py:120} INFO -   begin Extract >> CHARGEBACKS
[2022-11-12T13:40:34.546+0000] {logging_mixin.py:120} INFO - Error mientras extracción de datos: [Errno 2] No such file or directory: '/Users/napo/Documents/proyecto/Big Data/BigData/data/chargebacks'
[2022-11-12T13:40:34.550+0000] {logging_mixin.py:120} INFO -   >>end Extract CHARGEBACKS..
[2022-11-12T13:40:34.552+0000] {logging_mixin.py:120} INFO - [end] - EXTRACT-DATA
[2022-11-12T13:40:34.555+0000] {logging_mixin.py:120} INFO - >>El tiempo total de ejecucion del script [extract] es:     0.015863418579101562 Segundos
[2022-11-12T13:40:34.558+0000] {logging_mixin.py:120} INFO - [T]RANSFORM DATA
[2022-11-12T13:40:34.562+0000] {logging_mixin.py:120} INFO - Error mientras extracción de datos: (psycopg2.OperationalError) connection to server at "localhost" (127.0.0.1), port 5438 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5438 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2022-11-12T13:40:34.570+0000] {logging_mixin.py:120} INFO - [L]OAD DATA 
[2022-11-12T13:40:34.574+0000] {logging_mixin.py:120} INFO - Error mientras extracción de datos: (psycopg2.OperationalError) connection to server at "localhost" (127.0.0.1), port 5438 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5438 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2022-11-12T13:40:34.594+0000] {logging_mixin.py:120} INFO - [2022-11-12T13:40:34.587+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl.py", line 37, in <module>
    python_callable=extract
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 408, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 162, in __init__
    raise AirflowException('`python_callable` param must be callable')
airflow.exceptions.AirflowException: `python_callable` param must be callable
[2022-11-12T13:40:34.610+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/etl.py
[2022-11-12T13:40:34.679+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/etl.py took 0.657 seconds
[2022-11-12T13:41:05.034+0000] {processor.py:154} INFO - Started process (PID=320) to work on /opt/airflow/dags/etl.py
[2022-11-12T13:41:05.036+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2022-11-12T13:41:05.038+0000] {logging_mixin.py:120} INFO - [2022-11-12T13:41:05.038+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2022-11-12T13:41:05.459+0000] {logging_mixin.py:120} INFO - Grupo 99 ....>> runing ETL
[2022-11-12T13:41:05.461+0000] {logging_mixin.py:120} INFO - [E]XTRACT DATA
[2022-11-12T13:41:05.462+0000] {logging_mixin.py:120} INFO -   begin Extract >> PAYMENTS
[2022-11-12T13:41:05.465+0000] {logging_mixin.py:120} INFO - Error mientras extracción de datos: [Errno 2] No such file or directory: '/Users/napo/Documents/proyecto/Big Data/BigData/data/payments'
[2022-11-12T13:41:05.468+0000] {logging_mixin.py:120} INFO -   >>end Extract PAYMENTS..
[2022-11-12T13:41:05.470+0000] {logging_mixin.py:120} INFO -   begin Extract >> CHARGEBACKS
[2022-11-12T13:41:05.471+0000] {logging_mixin.py:120} INFO - Error mientras extracción de datos: [Errno 2] No such file or directory: '/Users/napo/Documents/proyecto/Big Data/BigData/data/chargebacks'
[2022-11-12T13:41:05.472+0000] {logging_mixin.py:120} INFO -   >>end Extract CHARGEBACKS..
[2022-11-12T13:41:05.473+0000] {logging_mixin.py:120} INFO - [end] - EXTRACT-DATA
[2022-11-12T13:41:05.474+0000] {logging_mixin.py:120} INFO - >>El tiempo total de ejecucion del script [extract] es:     0.014015436172485352 Segundos
[2022-11-12T13:41:05.476+0000] {logging_mixin.py:120} INFO - [T]RANSFORM DATA
[2022-11-12T13:41:05.478+0000] {logging_mixin.py:120} INFO - Error mientras extracción de datos: (psycopg2.OperationalError) connection to server at "localhost" (127.0.0.1), port 5438 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5438 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2022-11-12T13:41:05.483+0000] {logging_mixin.py:120} INFO - [L]OAD DATA 
[2022-11-12T13:41:05.487+0000] {logging_mixin.py:120} INFO - Error mientras extracción de datos: (psycopg2.OperationalError) connection to server at "localhost" (127.0.0.1), port 5438 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5438 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2022-11-12T13:41:05.501+0000] {logging_mixin.py:120} INFO - [2022-11-12T13:41:05.496+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl.py", line 37, in <module>
    python_callable=extract
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 408, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 162, in __init__
    raise AirflowException('`python_callable` param must be callable')
airflow.exceptions.AirflowException: `python_callable` param must be callable
[2022-11-12T13:41:05.504+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/etl.py
[2022-11-12T13:41:05.539+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/etl.py took 0.515 seconds
[2022-11-12T13:41:35.675+0000] {processor.py:154} INFO - Started process (PID=333) to work on /opt/airflow/dags/etl.py
[2022-11-12T13:41:35.678+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2022-11-12T13:41:35.683+0000] {logging_mixin.py:120} INFO - [2022-11-12T13:41:35.683+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2022-11-12T13:41:36.106+0000] {logging_mixin.py:120} INFO - Grupo 99 ....>> runing ETL
[2022-11-12T13:41:36.107+0000] {logging_mixin.py:120} INFO - [E]XTRACT DATA
[2022-11-12T13:41:36.108+0000] {logging_mixin.py:120} INFO -   begin Extract >> PAYMENTS
[2022-11-12T13:41:36.110+0000] {logging_mixin.py:120} INFO - Error mientras extracción de datos: [Errno 2] No such file or directory: '/Users/napo/Documents/proyecto/Big Data/BigData/data/payments'
[2022-11-12T13:41:36.111+0000] {logging_mixin.py:120} INFO -   >>end Extract PAYMENTS..
[2022-11-12T13:41:36.112+0000] {logging_mixin.py:120} INFO -   begin Extract >> CHARGEBACKS
[2022-11-12T13:41:36.114+0000] {logging_mixin.py:120} INFO - Error mientras extracción de datos: [Errno 2] No such file or directory: '/Users/napo/Documents/proyecto/Big Data/BigData/data/chargebacks'
[2022-11-12T13:41:36.116+0000] {logging_mixin.py:120} INFO -   >>end Extract CHARGEBACKS..
[2022-11-12T13:41:36.117+0000] {logging_mixin.py:120} INFO - [end] - EXTRACT-DATA
[2022-11-12T13:41:36.118+0000] {logging_mixin.py:120} INFO - >>El tiempo total de ejecucion del script [extract] es:     0.01235508918762207 Segundos
[2022-11-12T13:41:36.121+0000] {logging_mixin.py:120} INFO - [T]RANSFORM DATA
[2022-11-12T13:41:36.125+0000] {logging_mixin.py:120} INFO - Error mientras extracción de datos: (psycopg2.OperationalError) connection to server at "localhost" (127.0.0.1), port 5438 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5438 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2022-11-12T13:41:36.127+0000] {logging_mixin.py:120} INFO - [L]OAD DATA 
[2022-11-12T13:41:36.130+0000] {logging_mixin.py:120} INFO - Error mientras extracción de datos: (psycopg2.OperationalError) connection to server at "localhost" (127.0.0.1), port 5438 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5438 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2022-11-12T13:41:36.146+0000] {logging_mixin.py:120} INFO - [2022-11-12T13:41:36.141+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl.py", line 37, in <module>
    python_callable=extract
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 408, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 162, in __init__
    raise AirflowException('`python_callable` param must be callable')
airflow.exceptions.AirflowException: `python_callable` param must be callable
[2022-11-12T13:41:36.149+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/etl.py
[2022-11-12T13:41:36.187+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/etl.py took 0.520 seconds
[2022-11-12T13:42:06.491+0000] {processor.py:154} INFO - Started process (PID=353) to work on /opt/airflow/dags/etl.py
[2022-11-12T13:42:06.508+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2022-11-12T13:42:06.523+0000] {logging_mixin.py:120} INFO - [2022-11-12T13:42:06.522+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2022-11-12T13:42:07.437+0000] {logging_mixin.py:120} INFO - Grupo 99 ....>> runing ETL
[2022-11-12T13:42:07.440+0000] {logging_mixin.py:120} INFO - [E]XTRACT DATA
[2022-11-12T13:42:07.442+0000] {logging_mixin.py:120} INFO -   begin Extract >> PAYMENTS
[2022-11-12T13:42:07.444+0000] {logging_mixin.py:120} INFO - Error mientras extracción de datos: [Errno 2] No such file or directory: '/Users/napo/Documents/proyecto/Big Data/BigData/data/payments'
[2022-11-12T13:42:07.445+0000] {logging_mixin.py:120} INFO -   >>end Extract PAYMENTS..
[2022-11-12T13:42:07.447+0000] {logging_mixin.py:120} INFO -   begin Extract >> CHARGEBACKS
[2022-11-12T13:42:07.450+0000] {logging_mixin.py:120} INFO - Error mientras extracción de datos: [Errno 2] No such file or directory: '/Users/napo/Documents/proyecto/Big Data/BigData/data/chargebacks'
[2022-11-12T13:42:07.453+0000] {logging_mixin.py:120} INFO -   >>end Extract CHARGEBACKS..
[2022-11-12T13:42:07.454+0000] {logging_mixin.py:120} INFO - [end] - EXTRACT-DATA
[2022-11-12T13:42:07.456+0000] {logging_mixin.py:120} INFO - >>El tiempo total de ejecucion del script [extract] es:     0.018672943115234375 Segundos
[2022-11-12T13:42:07.459+0000] {logging_mixin.py:120} INFO - [T]RANSFORM DATA
[2022-11-12T13:42:07.462+0000] {logging_mixin.py:120} INFO - Error mientras extracción de datos: (psycopg2.OperationalError) connection to server at "localhost" (127.0.0.1), port 5438 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5438 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2022-11-12T13:42:07.467+0000] {logging_mixin.py:120} INFO - [L]OAD DATA 
[2022-11-12T13:42:07.471+0000] {logging_mixin.py:120} INFO - Error mientras extracción de datos: (psycopg2.OperationalError) connection to server at "localhost" (127.0.0.1), port 5438 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5438 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2022-11-12T13:42:07.487+0000] {logging_mixin.py:120} INFO - [2022-11-12T13:42:07.482+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl.py", line 37, in <module>
    python_callable=extract
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 408, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 162, in __init__
    raise AirflowException('`python_callable` param must be callable')
airflow.exceptions.AirflowException: `python_callable` param must be callable
[2022-11-12T13:42:07.489+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/etl.py
[2022-11-12T13:42:07.526+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/etl.py took 1.048 seconds
[2022-11-12T13:42:37.923+0000] {processor.py:154} INFO - Started process (PID=373) to work on /opt/airflow/dags/etl.py
[2022-11-12T13:42:37.926+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2022-11-12T13:42:37.928+0000] {logging_mixin.py:120} INFO - [2022-11-12T13:42:37.928+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2022-11-12T13:42:38.941+0000] {logging_mixin.py:120} INFO - Grupo 99 ....>> runing ETL
[2022-11-12T13:42:38.956+0000] {logging_mixin.py:120} INFO - [E]XTRACT DATA
[2022-11-12T13:42:38.958+0000] {logging_mixin.py:120} INFO -   begin Extract >> PAYMENTS
[2022-11-12T13:42:38.959+0000] {logging_mixin.py:120} INFO - Error mientras extracción de datos: [Errno 2] No such file or directory: '/Users/napo/Documents/proyecto/Big Data/BigData/data/payments'
[2022-11-12T13:42:38.961+0000] {logging_mixin.py:120} INFO -   >>end Extract PAYMENTS..
[2022-11-12T13:42:38.962+0000] {logging_mixin.py:120} INFO -   begin Extract >> CHARGEBACKS
[2022-11-12T13:42:38.970+0000] {logging_mixin.py:120} INFO - Error mientras extracción de datos: [Errno 2] No such file or directory: '/Users/napo/Documents/proyecto/Big Data/BigData/data/chargebacks'
[2022-11-12T13:42:38.972+0000] {logging_mixin.py:120} INFO -   >>end Extract CHARGEBACKS..
[2022-11-12T13:42:38.973+0000] {logging_mixin.py:120} INFO - [end] - EXTRACT-DATA
[2022-11-12T13:42:38.986+0000] {logging_mixin.py:120} INFO - >>El tiempo total de ejecucion del script [extract] es:     0.03523063659667969 Segundos
[2022-11-12T13:42:38.991+0000] {logging_mixin.py:120} INFO - [T]RANSFORM DATA
[2022-11-12T13:42:38.994+0000] {logging_mixin.py:120} INFO - Error mientras extracción de datos: (psycopg2.OperationalError) connection to server at "localhost" (127.0.0.1), port 5438 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5438 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2022-11-12T13:42:39.003+0000] {logging_mixin.py:120} INFO - [L]OAD DATA 
[2022-11-12T13:42:39.006+0000] {logging_mixin.py:120} INFO - Error mientras extracción de datos: (psycopg2.OperationalError) connection to server at "localhost" (127.0.0.1), port 5438 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5438 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2022-11-12T13:42:39.028+0000] {logging_mixin.py:120} INFO - [2022-11-12T13:42:39.024+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl.py", line 37, in <module>
    python_callable=extract
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 408, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 162, in __init__
    raise AirflowException('`python_callable` param must be callable')
airflow.exceptions.AirflowException: `python_callable` param must be callable
[2022-11-12T13:42:39.030+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/etl.py
[2022-11-12T13:42:39.124+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/etl.py took 1.207 seconds
[2022-11-12T13:43:09.715+0000] {processor.py:154} INFO - Started process (PID=384) to work on /opt/airflow/dags/etl.py
[2022-11-12T13:43:09.718+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2022-11-12T13:43:09.721+0000] {logging_mixin.py:120} INFO - [2022-11-12T13:43:09.721+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2022-11-12T13:43:10.066+0000] {logging_mixin.py:120} INFO - Grupo 99 ....>> runing ETL
[2022-11-12T13:43:10.067+0000] {logging_mixin.py:120} INFO - [E]XTRACT DATA
[2022-11-12T13:43:10.068+0000] {logging_mixin.py:120} INFO -   begin Extract >> PAYMENTS
[2022-11-12T13:43:10.069+0000] {logging_mixin.py:120} INFO - Error mientras extracción de datos: [Errno 2] No such file or directory: '/Users/napo/Documents/proyecto/Big Data/BigData/data/payments'
[2022-11-12T13:43:10.070+0000] {logging_mixin.py:120} INFO -   >>end Extract PAYMENTS..
[2022-11-12T13:43:10.071+0000] {logging_mixin.py:120} INFO -   begin Extract >> CHARGEBACKS
[2022-11-12T13:43:10.072+0000] {logging_mixin.py:120} INFO - Error mientras extracción de datos: [Errno 2] No such file or directory: '/Users/napo/Documents/proyecto/Big Data/BigData/data/chargebacks'
[2022-11-12T13:43:10.073+0000] {logging_mixin.py:120} INFO -   >>end Extract CHARGEBACKS..
[2022-11-12T13:43:10.074+0000] {logging_mixin.py:120} INFO - [end] - EXTRACT-DATA
[2022-11-12T13:43:10.075+0000] {logging_mixin.py:120} INFO - >>El tiempo total de ejecucion del script [extract] es:     0.009137392044067383 Segundos
[2022-11-12T13:43:10.078+0000] {logging_mixin.py:120} INFO - [T]RANSFORM DATA
[2022-11-12T13:43:10.080+0000] {logging_mixin.py:120} INFO - Error mientras extracción de datos: (psycopg2.OperationalError) connection to server at "localhost" (127.0.0.1), port 5438 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5438 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2022-11-12T13:43:10.083+0000] {logging_mixin.py:120} INFO - [L]OAD DATA 
[2022-11-12T13:43:10.086+0000] {logging_mixin.py:120} INFO - Error mientras extracción de datos: (psycopg2.OperationalError) connection to server at "localhost" (127.0.0.1), port 5438 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5438 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2022-11-12T13:43:10.100+0000] {logging_mixin.py:120} INFO - [2022-11-12T13:43:10.094+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl.py", line 37, in <module>
    python_callable=extract
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 408, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 162, in __init__
    raise AirflowException('`python_callable` param must be callable')
airflow.exceptions.AirflowException: `python_callable` param must be callable
[2022-11-12T13:43:10.103+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/etl.py
[2022-11-12T13:43:10.143+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/etl.py took 0.436 seconds
[2022-11-12T13:43:40.475+0000] {processor.py:154} INFO - Started process (PID=395) to work on /opt/airflow/dags/etl.py
[2022-11-12T13:43:40.480+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2022-11-12T13:43:40.484+0000] {logging_mixin.py:120} INFO - [2022-11-12T13:43:40.484+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2022-11-12T13:43:40.979+0000] {logging_mixin.py:120} INFO - Grupo 99 ....>> runing ETL
[2022-11-12T13:43:40.981+0000] {logging_mixin.py:120} INFO - [E]XTRACT DATA
[2022-11-12T13:43:40.981+0000] {logging_mixin.py:120} INFO -   begin Extract >> PAYMENTS
[2022-11-12T13:43:40.982+0000] {logging_mixin.py:120} INFO - Error mientras extracción de datos: [Errno 2] No such file or directory: '/Users/napo/Documents/proyecto/Big Data/BigData/data/payments'
[2022-11-12T13:43:40.983+0000] {logging_mixin.py:120} INFO -   >>end Extract PAYMENTS..
[2022-11-12T13:43:40.984+0000] {logging_mixin.py:120} INFO -   begin Extract >> CHARGEBACKS
[2022-11-12T13:43:40.985+0000] {logging_mixin.py:120} INFO - Error mientras extracción de datos: [Errno 2] No such file or directory: '/Users/napo/Documents/proyecto/Big Data/BigData/data/chargebacks'
[2022-11-12T13:43:40.987+0000] {logging_mixin.py:120} INFO -   >>end Extract CHARGEBACKS..
[2022-11-12T13:43:40.991+0000] {logging_mixin.py:120} INFO - [end] - EXTRACT-DATA
[2022-11-12T13:43:40.994+0000] {logging_mixin.py:120} INFO - >>El tiempo total de ejecucion del script [extract] es:     0.01481175422668457 Segundos
[2022-11-12T13:43:40.998+0000] {logging_mixin.py:120} INFO - [T]RANSFORM DATA
[2022-11-12T13:43:41.002+0000] {logging_mixin.py:120} INFO - Error mientras extracción de datos: (psycopg2.OperationalError) connection to server at "localhost" (127.0.0.1), port 5438 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5438 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2022-11-12T13:43:41.007+0000] {logging_mixin.py:120} INFO - [L]OAD DATA 
[2022-11-12T13:43:41.011+0000] {logging_mixin.py:120} INFO - Error mientras extracción de datos: (psycopg2.OperationalError) connection to server at "localhost" (127.0.0.1), port 5438 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5438 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2022-11-12T13:43:41.029+0000] {logging_mixin.py:120} INFO - [2022-11-12T13:43:41.024+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl.py", line 37, in <module>
    python_callable=extract
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 408, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 162, in __init__
    raise AirflowException('`python_callable` param must be callable')
airflow.exceptions.AirflowException: `python_callable` param must be callable
[2022-11-12T13:43:41.032+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/etl.py
[2022-11-12T13:43:41.068+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/etl.py took 0.602 seconds
[2022-11-12T13:44:11.895+0000] {processor.py:154} INFO - Started process (PID=406) to work on /opt/airflow/dags/etl.py
[2022-11-12T13:44:11.899+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2022-11-12T13:44:11.901+0000] {logging_mixin.py:120} INFO - [2022-11-12T13:44:11.901+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2022-11-12T13:44:12.318+0000] {logging_mixin.py:120} INFO - Grupo 99 ....>> runing ETL
[2022-11-12T13:44:12.320+0000] {logging_mixin.py:120} INFO - [E]XTRACT DATA
[2022-11-12T13:44:12.321+0000] {logging_mixin.py:120} INFO -   begin Extract >> PAYMENTS
[2022-11-12T13:44:12.323+0000] {logging_mixin.py:120} INFO - Error mientras extracción de datos: [Errno 2] No such file or directory: '/Users/napo/Documents/proyecto/Big Data/BigData/data/payments'
[2022-11-12T13:44:12.325+0000] {logging_mixin.py:120} INFO -   >>end Extract PAYMENTS..
[2022-11-12T13:44:12.326+0000] {logging_mixin.py:120} INFO -   begin Extract >> CHARGEBACKS
[2022-11-12T13:44:12.328+0000] {logging_mixin.py:120} INFO - Error mientras extracción de datos: [Errno 2] No such file or directory: '/Users/napo/Documents/proyecto/Big Data/BigData/data/chargebacks'
[2022-11-12T13:44:12.329+0000] {logging_mixin.py:120} INFO -   >>end Extract CHARGEBACKS..
[2022-11-12T13:44:12.330+0000] {logging_mixin.py:120} INFO - [end] - EXTRACT-DATA
[2022-11-12T13:44:12.331+0000] {logging_mixin.py:120} INFO - >>El tiempo total de ejecucion del script [extract] es:     0.012515783309936523 Segundos
[2022-11-12T13:44:12.334+0000] {logging_mixin.py:120} INFO - [T]RANSFORM DATA
[2022-11-12T13:44:12.337+0000] {logging_mixin.py:120} INFO - Error mientras extracción de datos: (psycopg2.OperationalError) connection to server at "localhost" (127.0.0.1), port 5438 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5438 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2022-11-12T13:44:12.340+0000] {logging_mixin.py:120} INFO - [L]OAD DATA 
[2022-11-12T13:44:12.344+0000] {logging_mixin.py:120} INFO - Error mientras extracción de datos: (psycopg2.OperationalError) connection to server at "localhost" (127.0.0.1), port 5438 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5438 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2022-11-12T13:44:12.359+0000] {logging_mixin.py:120} INFO - [2022-11-12T13:44:12.353+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl.py", line 37, in <module>
    python_callable=extract
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 408, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 162, in __init__
    raise AirflowException('`python_callable` param must be callable')
airflow.exceptions.AirflowException: `python_callable` param must be callable
[2022-11-12T13:44:12.361+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/etl.py
[2022-11-12T13:44:12.396+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/etl.py took 0.509 seconds
