[2022-11-12T13:52:19.132+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: ETL.Extract manual__2022-11-12T13:52:15.455404+00:00 [queued]>
[2022-11-12T13:52:19.148+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: ETL.Extract manual__2022-11-12T13:52:15.455404+00:00 [queued]>
[2022-11-12T13:52:19.149+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-11-12T13:52:19.150+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2022-11-12T13:52:19.151+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-11-12T13:52:19.175+0000] {taskinstance.py:1383} INFO - Executing <Task(PythonOperator): Extract> on 2022-11-12 13:52:15.455404+00:00
[2022-11-12T13:52:19.184+0000] {standard_task_runner.py:55} INFO - Started process 245 to run task
[2022-11-12T13:52:19.192+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'ETL', 'Extract', 'manual__2022-11-12T13:52:15.455404+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/DAG_etl.py', '--cfg-path', '/tmp/tmpfdf2x8t1']
[2022-11-12T13:52:19.196+0000] {standard_task_runner.py:83} INFO - Job 3: Subtask Extract
[2022-11-12T13:52:19.299+0000] {task_command.py:376} INFO - Running <TaskInstance: ETL.Extract manual__2022-11-12T13:52:15.455404+00:00 [running]> on host 955246a8353f
[2022-11-12T13:52:19.535+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=ETL
AIRFLOW_CTX_TASK_ID=Extract
AIRFLOW_CTX_EXECUTION_DATE=2022-11-12T13:52:15.455404+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-11-12T13:52:15.455404+00:00
[2022-11-12T13:52:19.544+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 193, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
TypeError: extract() missing 1 required positional argument: 'path'
[2022-11-12T13:52:19.620+0000] {taskinstance.py:1406} INFO - Marking task as FAILED. dag_id=ETL, task_id=Extract, execution_date=20221112T135215, start_date=20221112T135219, end_date=20221112T135219
[2022-11-12T13:52:19.665+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 3 for task Extract (extract() missing 1 required positional argument: 'path'; 245)
[2022-11-12T13:52:19.751+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2022-11-12T13:52:20.038+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
